### ISSUE TITLE
【bug】数据写入缓存后读取的内容与原数据不一致。

### ISSUE THREAD

**Issue by YaChengMu** [NewLifeX/NewLife.Redis#105]
![image](https://github.com/NewLifeX/NewLife.Redis/assets/9545729/4e319f38-9971-4470-bba7-d41070edf88a)
[ConsoleApp1.zip](https://github.com/NewLifeX/NewLife.Redis/files/11459171/ConsoleApp1.zip)

**Comment by nnhy** [comment]
经过序列化以后，内容可能有所不同。
你把前后两个json对比一下，或者贴出来看看

**Comment by ligengrong** [comment]
aa == bb  替换成 Newtonsoft.Json.JsonConvert.SerializeObject(tt) == bb，应该就没问题了，
因为你字符串转List，再Set进去的json未必和你手写字符串一样

**Comment by YaChengMu** [comment]
[ConsoleApp1.zip](https://github.com/NewLifeX/NewLife.Redis/files/11459437/ConsoleApp1.zip)
前一个demo写的有点问题，我重新调整了一下。

**Comment by ligengrong** [comment]
您的代码大概看了下，是内置的ToJson深度超了，您可以这样解决
1、.Net 5.0以上的，可以在程序启动是替换Json默认实现为SystemJson
