### ISSUE TITLE
经常出现超时问题

### ISSUE THREAD

**Issue by 840900649** [NewLifeX/NewLife.Redis#11]
运行时经常出现超时问题，导致页面无法访问。有时登录时候因超时，用户以为系统BUG。无法访问。有什么解决方案吗？

**Comment by nnhy** [comment]
可有相关日志？
该项目每天数十亿级别的Redis操作，稳定工作一年半。
如果出现超时，有可能是执行了非常耗时的操作

**Comment by 840900649** [comment]
有日志，不过或许是，远程连接阿里服务器。 中间出现了某种错误。

**Comment by nnhy** [comment]
阿里云Redis集群测试通过，可以更新版本试试。
如果还有问题，可以提交详细日志
