### ISSUE TITLE
延迟队列是不是不可以消息确认才删除

### ISSUE THREAD

**Issue by ZevFung** [NewLifeX/NewLife.Redis#112]
我运行DelayQueue.cs demo，发现queue.Acknowledge(mqMsg);不起效果。
源码RedisDelayQueue的   Acknowledge 没有具体实现，直接返回-1
    /// <summary>确认删除</summary>
    /// <param name="keys"></param>
    /// <returns></returns>
    public Int32 Acknowledge(params T[] keys) => -1;

而RedisReliableQueue 可以

延迟队列是不是不可以消息确认才删除？

**Comment by nnhy** [comment]
延迟队列使用ZSET实现，不好设计确认删除功能。
或者你有更好的想法，也可以一起讨论实现。

**Comment by ZevFung** [comment]
看了下RedisReliableQueue有高级队列用法，初始化延迟队列InitDelay，里面会定时查询延迟队列是否有消息，有则把已到期消息转移到可靠Redis队列

**Comment by nnhy** [comment]
是的，延迟队列独立使用比较难用，一般配合可信队列。
我们也在思考更好的架构，欢迎提供更好的想法
