### ISSUE TITLE
Which NewLife.Redis versions supports Redis 7.0?

### ISSUE THREAD

**Issue by jeroenhabets** [NewLifeX/NewLife.Redis#115]
Main question of #107 I could not find an answer for:
> We're now contemplating updating our Redis from 6.2 to 7.0 and I tried to find out which Redis versions you support. I.e. from which version onward is 7.0 supported? And does upgrading your library have any breaking changes?

@Soar360 or @nnhy Can you share from which NewLife.Redis version onward it supports Redis 7.0?
(Or are there no breaking protocol changes and we can use any version of the last two years)

**Comment by nnhy** [comment]
vx.x.2003.x
