### ISSUE TITLE
.Net8 support

### ISSUE THREAD

**Issue by jeroenhabets** [NewLifeX/NewLife.Redis#116]
Hi @nnhy, @Soar360, do plan to release a NewLife.Redis version targeting `net8.0` soon? Cheers

**Comment by jeroenhabets** [comment]
FYI: Already got an answer for its sibling https://github.com/NewLifeX/NewLife.Redis.Core/issues/3
> If .NET 8.0 is released, we will upgrade it as soon as possible.

**Comment by jeroenhabets** [comment]
@nnhy (@Soar360) I agree it would be an "enhancement" for this library to (conditionally) make use of all the modern APIs and optimizations if it were also targeting "net8.0".

Are there any new APIs you'd expect a significant boost from?

**Comment by nnhy** [comment]
No new API added

**Comment by nnhy** [comment]
Already supports. net8.0 and will support. net9.0 by the end of this year
