### ISSUE TITLE
使用 List 設定 expire 沒有作用  ?

### ISSUE THREAD

**Issue by cashwu** [NewLifeX/NewLife.Redis#117]
NewLife.Redis Version="5.5.2023.1001"

下面是我的測試程式碼

```csharp
var fullRedis = new FullRedis("127.0.0.1:6379", "", 0);
        
var key = "test_list";
fullRedis.Remove(key);

var list = fullRedis.GetList<DateTime>(key);
fullRedis.SetExpire(key, TimeSpan.FromSeconds(60));

list.Add(DateTime.Now);
list.Add(DateTime.Now.AddSeconds(5));
```

看 redis 的結果，TTL 還是 `-1` 不確定我的程式碼那裡有問題 ? 還是 `SetExpire` 的方式有問題 ?

<img width="829" alt="image" src="https://github.com/NewLifeX/NewLife.Redis/assets/4278751/66a79c20-405a-4407-9800-0485928f9a9e">

**Comment by nnhy** [comment]
redis不允许存在空LIST，所以开始就设置有效期是无效的。
可以在添加原始以后，再设置有效期。
同理，如果LIST里面的元素被清空，那么LIST也就不存在了，下次添加元素的时候，需要再次设置有效期。

**Comment by cashwu** [comment]
了解，剛才試了一下，添加元素後在設置有效期就可以了
用 NewLife.Redis 專案裡面的 xunit test 程式測試，沒想到反而被誤導了
感謝你的回答和協助
