### ISSUE TITLE
怎么读取STREAM数据

### ISSUE THREAD

**Issue by pinzi** [NewLifeX/NewLife.Redis#118]
使用GetStream方法读取出来的数据不是JSON格式，这是怎么回事呢？

![image](https://github.com/NewLifeX/NewLife.Redis/assets/3843463/1de298dc-8bb5-40aa-b7e0-a131bb8d7e50)

![image](https://github.com/NewLifeX/NewLife.Redis/assets/3843463/e0a021a7-90f9-4396-bd16-5fe128fec7fb)

![image](https://github.com/NewLifeX/NewLife.Redis/assets/3843463/8929e5f2-34de-49b0-a53f-bb3eff62ff6b)

**Comment by nnhy** [comment]
redisStream存储的数据是字符串数组，比较诡异
