### ISSUE TITLE
RedisStream<T>.Range(DateTime start, DateTime end, Int32 count = -1)读取的消息不是时间区间内的？

### ISSUE THREAD

**Issue by pinzi** [NewLifeX/NewLife.Redis#119]
![image](https://github.com/NewLifeX/NewLife.Redis/assets/3843463/c07817c6-d105-4137-9ef0-ae644aeaf720)
获取的是六个小时以前的数据，为啥最新的数据也获取到了呢？
![image](https://github.com/NewLifeX/NewLife.Redis/assets/3843463/b240edf1-3a36-4234-aaca-cd7b5b0881d0)

**Comment by nnhy** [comment]
这个方法没有做单元测试，可能是一个bug。
你可以把指令日至打印出来看看

**Comment by nnhy** [comment]
var redis=new FullRedis(xxx);
redis.Log = XTrace.Log;
redis.ClientLog = XTrace.Log;

打开客户端日志，执行Range命令时，将会在日志看到它发送的命令，然后就知道用哪个时区了

**Comment by pinzi** [comment]
![image](https://github.com/NewLifeX/NewLife.Redis/assets/3843463/5a69d2e9-7755-429a-a176-97a772e19b24)
之前我用的时候发现直接用当前时区的时间得到的数据时间不是最近的，我就转成UTC时间解决了。
现在测试发现已经没有这个问题了
![image](https://github.com/NewLifeX/NewLife.Redis/assets/3843463/39b82644-8af4-438f-a7d8-8a0f9b7ea7aa)

**Comment by pinzi** [comment]
![image](https://github.com/NewLifeX/NewLife.Redis/assets/3843463/74f7aab2-72bd-4ba5-ac1f-cba32220ea3d)
日志也看不出来是哪个时区的啊？

**Comment by pinzi** [comment]
![image](https://github.com/NewLifeX/NewLife.Redis/assets/3843463/8a514045-e4ec-4f79-b1bf-9ba5c6c0b19f)
IOC的方式为啥日志不起作用呢？

**Comment by pinzi** [comment]
![image](https://github.com/NewLifeX/NewLife.Redis/assets/3843463/2cc9912d-ea56-483a-8703-84b9f5d09ad7)
![image](https://github.com/NewLifeX/NewLife.Redis/assets/3843463/9764dd54-6db7-43a1-afba-f93049845a0d)
最新版还有这么一个bug，之前的版本5.5的反而没有这个问题

**Comment by nnhy** [comment]
关于时间时区的问题，redis和json序列化根本就没有处理时区，你存进去的是啥，读取出来就是啥，当然需要你自己处理。
RedisStream的id是redis内部生成，使用了UTC的Unix时间，传入当前时间时要处理一下。

**Comment by nnhy** [comment]
> ![image](https://private-user-images.githubusercontent.com/3843463/296146198-8a514045-e4ec-4f79-b1bf-9ba5c6c0b19f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MzQzMjAsIm5iZiI6MTcwNTczNDAyMCwicGF0aCI6Ii8zODQzNDYzLzI5NjE0NjE5OC04YTUxNDA0NS1lNGVjLTRmNzktYjFiZi05YmE1YzZjMGIxOWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjBUMDcwMDIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTMzYTIxN2E3ZmEzNThkNjc0M2RjZTViZjNkZDJiZWQ1ZGU3MDk3ZWM1NTNmYjlhMmY2ZDYzYzZmYWRhNTIxYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.twyjJMOUczN3F-iNvuWY_PQmnlt11QZ5v6Thj-_S_2Y) IOC的方式为啥日志不起作用呢？

关于这个问题，XTrace.UseConsole必须放在第一行，所有代码直线，否则无法把日志输出到控制台

**Comment by nnhy** [comment]
XTrace.UseConsole必须放在第一行，所有代码之前，否则无法把日志输出到控制台
