### ISSUE TITLE
开启管道提交(AutoPipeline)问题

### ISSUE THREAD

**Issue by xueandfeng** [NewLifeX/NewLife.Redis#12]
![default](https://user-images.githubusercontent.com/20178645/50829696-4cfe8100-1380-11e9-89aa-721d86999c76.png)
目前我只要这个DB指定0 Get方法获取不到值。用Commit()方法提交都没有用.
把DB值设置大于0就没问问题。不知道是否我使用问题

**Comment by nnhy** [comment]
关闭 AutoPipeline 试试

**Comment by xueandfeng** [comment]
关闭AutoPipeline是正常的

**Comment by nnhy** [comment]
问题出在 AutoPipeline 上，它会缓存所有写入操作，然后整批发送，因此你Set以后，它压根就没有执行，而是延后了。
调用 Commit 可以马上提交
