### ISSUE TITLE
集群模式下，批量删除key会报错

### ISSUE THREAD

**Issue by jackehuang** [NewLifeX/NewLife.Redis#120]
System.Exception
  HResult=0x80131500
  Message=CROSSSLOT Keys in request don't hash to the same slot
  Source=NewLife.Redis
  StackTrace:
   在 NewLife.Caching.RedisClient.GetResponse(Stream ns, Int32 count)
   在 NewLife.Caching.RedisClient.ExecuteCommand(String cmd, Packet[] args, Object[] oriArgs)
   在 NewLife.Caching.RedisClient.Execute(String cmd, Object[] args)
   在 NewLife.Caching.RedisClient.Execute[TResult](String cmd, Object[] args)
   在 NewLife.Caching.FullRedis.Execute[T](String key, Func`3 func, Boolean write)
   在 NewLife.Caching.Redis.Remove(String[] keys)

**Comment by microsofter** [comment]
已经收到您的来信，我会尽快回复。
