### ISSUE TITLE
连接[://192.168.0.32:3838][3000ms]超时！

### ISSUE THREAD

**Issue by qinweizhen1** [NewLifeX/NewLife.Redis#126]
注入：
 ICache cache = Cache.Default;
  var redis = new FullRedis();
  redis.Init(cacheOptions.RedisConnectionString);
  cache = redis;
 services.AddSingleton(cache);

当我在其他地方使用：((FullRedis)cache).Search($"{prefixKey}*", int.MaxValue).ToList(); 时就会出现 连接[://192.168.0.32:3838][3000ms]超时！错误，但是我的redis地址不是这个。不明白为什么会出现这种错误

**Comment by microsofter** [comment]
已经收到您的来信，我会尽快回复。

**Comment by nnhy** [comment]
可能使用了Redis主从和代理等架构，FullRedis自动探测得到从机地址，特别是云服务Redis很常见这种架构。
可以通过AutoDetect来关闭。
redis.AutoDetect=false;

这个月版本（测试版）nuget包已经把AutoDetect默认值由true修改为false

**Comment by qinweizhen1** [comment]
是的，通过源码测试确实如此，已解决。感谢
