### ISSUE TITLE
配置多个redis地址时，如果第一个地址无法访问是不是不会自动切换。

### ISSUE THREAD

**Issue by 109214114** [NewLifeX/NewLife.Redis#127]
配置多个redis地址，第一个地址访问不了的时候，会一直提示请求超时不会自动切换。如果第一个位置的redis地址正常，其他位置无法连接的时候可以自动切换。
问一下这个是我使用方式不对吗。

**Comment by nnhy** [comment]
任意地址无法访问，都能够自动切换。
只是可能后台的AutoDetect在检测集群和主从节点，导致出现的超时日志

**Comment by 109214114** [comment]
> 时日志
![QQ截图20240403090011](https://github.com/NewLifeX/NewLife.Redis/assets/24285448/ebc2578c-4ce6-4124-b88d-68fb74d008eb)
那我这个测试代码当5000端口访问失败的时候，60秒之后还是 一直提示超时无法实现自动切换。

**Comment by nnhy** [comment]
rds.Log=XTrace.Log； 打开日志。
然后main函数入口加上 XTrace.UseConsole()。
再测试看看，此时能看到它的所有操作记录

**Comment by nnhy** [comment]
第一个地址不通，无法探测集群信息
