### ISSUE TITLE
MemoryCache首次进行Set时候，设置过期时间无效

### ISSUE THREAD

**Issue by xueandfeng** [NewLifeX/NewLife.Redis#13]
https://github.com/NewLifeX/X/blob/master/NewLife.Core/Caching/MemoryCache.cs#L380
https://github.com/NewLifeX/X/blob/master/NewLife.Core/Threading/TimerX.cs#L162
首次进行set的时候时间是错误的。导致设置缓存过期时间无效
![image](https://user-images.githubusercontent.com/20178645/50892438-79c29f00-1439-11e9-831a-ab937f077656.png)

@nnhy

**Comment by nnhy** [comment]
这是 TimerX.Now 的BUG，已确认并改正！~

多线程下首次访问Now可能取得空时间 · NewLifeX/X@7e0f14f
https://github.com/NewLifeX/X/commit/7e0f14f2c88ffc575aa3347546b735bb70105787
