### ISSUE TITLE
字段数组有默认值的时候获取不到数据

### ISSUE THREAD

**Issue by ourhouzi** [NewLifeX/NewLife.Redis#131]
版本： 5.6.2024.508
我的实体里面有数组字段且有默认值为空数组的情况
 public string[] ProjectIds { get; set; } = [];
获取缓存数据  _icache.Get<List<Model>>(key); 的时候 ProjectIds 数据永远是空数组。 
我把默字段默认空数据去掉后就可以获取到数据了

**Comment by microsofter** [comment]
已经收到您的来信，我会尽快回复。

**Comment by nnhy** [comment]
问题已修复，并通过基础测试。
还请试用，有问题及时反馈。

**Comment by ourhouzi** [comment]
已经更新到最新版本，问题已经解决，非常感谢！！
