### ISSUE TITLE
TimeOnly类型写入到 redis之后，变成了一个json对象那种格式，读取redis之后获取到的值无法用TimeOnly接收。

### ISSUE THREAD

**Issue by OaimIsGnay** [NewLifeX/NewLife.Redis#132]
<img width="307" alt="image" src="https://github.com/NewLifeX/NewLife.Redis/assets/58240619/8381926f-ebe6-49a4-95a0-762b2cb57b61">
<img width="369" alt="image" src="https://github.com/NewLifeX/NewLife.Redis/assets/58240619/6e425e13-401e-4f20-b078-90a51e5b2be2">
<img width="311" alt="image" src="https://github.com/NewLifeX/NewLife.Redis/assets/58240619/4e1b9a7a-7e8c-4e64-80e2-fc57f207c095">

  public TimeOnly EffectiveStartTime { get; set; }
    public TimeOnly EffectiveEndTime { get; set; }

请问这个有计划优化一下吗？

**Comment by nnhy** [comment]
这是第二次用户反馈该问题。预计本周末解决

**Comment by OaimIsGnay** [comment]
> 这是第二次用户反馈该问题。预计本周末解决

谢谢，大佬。

**Comment by nnhy** [comment]
NewLife.Core 已更新，增加对 DateOnly/TimeOnly 的支持，你只需要更新它的Nuget引用即可。
NewLife.Redis 默认使用NewLife.Core的FastJson序列化，预计这个月会修改为SystemJson序列化。

**Comment by nnhy** [comment]
问题已修复，并通过基础测试。
还请试用，有问题及时反馈。
