### ISSUE TITLE
DelayQueue 列队问题

### ISSUE THREAD

**Issue by xin12023** [NewLifeX/NewLife.Redis#133]
创建了一个 DelayQueue 列队 
value：{"Id":17741492324117,"OrderNo":"superadmin","Type":"Orders","Addition":null,"CreateTime":"2024-07-12T13:20:10.0000000"}
score： 1720874520
确认时间已到达
读取时使用 _cacheQueue.Take(count)  count > 0
读取到的数量为0 

如果
value：{"Id":17741492324117,"OrderNo":"superadmin","Type":"Orders","Addition":null,"CreateTime":null}
score： 1720874520

读取使用
读取时使用 _cacheQueue.Take(count)  count > 0
可以正常被读取到

**Comment by microsofter** [comment]
已经收到您的来信，我会尽快回复。

**Comment by xin12023** [comment]
再次测试写入值
{"Id":17741492324117,"OrderNo":"superadmin","Type":"Orders","Addition":null,"CreateTime":"2024-07-12T18:50:10.0000000\u002B05:30"}
可以被弹出列队

**Comment by nnhy** [comment]
延迟队列，本质上使用了Redis的排序集合 ZSET，那个分数，就是消息到期时间的UTC毫秒值。
延迟队列DelayQueue内部会定期（很短）轮询该队列，查找分数达标的数据。
