### ISSUE TITLE
对于云服务，阿里云的redis分布式集群应该如何配置

### ISSUE THREAD

**Issue by jason000000001** [NewLifeX/NewLife.Redis#134]
对于云服务，阿里云的redis分布式集群应该如何配置，阿里云的分布式集群只提供了代理地址和直链地址。并没有提供哨兵和节点地址，请问fullredis该如何配置。

**Comment by nnhy** [comment]
这种情况，直接配置使用它的代理地址就好，然后关闭自动检测，也就是 FullRedis.AutoDetect=false。

如果不用代理地址，就配置多个节点地址，并打开自动检测 AutoDetect=true。

**Comment by jason000000001** [comment]
谢谢,理解了。
