### ISSUE TITLE
AckQueue 没有确认消费第二次读取不到

### ISSUE THREAD

**Issue by xiahanlin** [NewLifeX/NewLife.Redis#135]
var queue = redis.GetReliableQueue<string>(tablename);
queue.Take()

提前向队列写入数据。
测试程序读取后未确认消息直接退出。
再次启动测试程序读取队列是后面的消息。

**Comment by nnhy** [comment]
要等几分钟，在pending挂起队列的消息，才会重新回到主队列

**Comment by xiahanlin** [comment]
哦 ，那只能换一种方式实现了。 另外想问一下支持事务吗

**Comment by nnhy** [comment]
如果你想使用标准MQ功能，推荐使用RedisStream，它的功能更完整，要求redis5.0起。

另外，MQ一般不支持事务，rocketMQ对事务的支持，属于特殊情况。
在redis队列中，你可以自己控制确认，也就是可以变相实现事务的提交和回滚，决定权在于自己。
