### ISSUE TITLE
关于分布式锁的一些使用疑问

### ISSUE THREAD

**Issue by pidogc** [NewLifeX/NewLife.Redis#136]
![image](https://github.com/user-attachments/assets/6be01a8b-752c-400f-8d79-6a6cd120c235)
你好，我尝试使用该库的分布式锁，在普通的测试中并没有发现问题，当我打算写一写关于锁是否正确获得的测试时发现，无法有效拦截锁的获得，上图就是我的测试一部分，在for循环中模拟并发获得锁，我发现在该情况下，锁会重复获得，我不清楚是否我的使用有问题还是我的测试有问题，感谢各位多多指教

**Comment by microsofter** [comment]
已经收到您的来信，我会尽快回复。

**Comment by nnhy** [comment]
分布式锁的实现，没有这么简单。
你可以参考Redis.AcquireLock代码

**Comment by pidogc** [comment]
> 全局锁的实现，没有那么简单。 你可以参考Redis.AcquireLock代码

你好，我目前使用就是AcquireLock的方法，我还需要额外实现？

**Comment by pidogc** [comment]
你好，目前该库的分布式锁是否有使用Redlock算法？如果需要是否只能自己去实现？

**Comment by nnhy** [comment]
> > 全局锁的实现，没有那么简单。 你可以参考Redis.AcquireLock代码
> 
> 你好，我目前使用就是AcquireLock的方法，我还需要额外实现？

AcquireLock 直接就可以使用，没理解你遇到什么问题。

**Comment by pidogc** [comment]
> > > 全局锁的实现，没有那么简单。 你可以参考Redis.AcquireLock代码
> > 
> > 
> > 你好，我目前使用就是AcquireLock的方法，我还需要额外实现？
> 
> AcquireLock 直接就可以使用，没理解你遇到什么问题。

如果集群部署，目前我不确定是否还需要再实现redlock，之前的测试我调整后OK了

**Comment by nnhy** [comment]
即使是集群，我们锁定的是一个key，它会分布到某个分片上面，不影响使用
