### ISSUE TITLE
版本更新后问题

### ISSUE THREAD

**Issue by xin12023** [NewLifeX/NewLife.Redis#138]
相同的代码,从  5.7.2024.801 版升级到 6.0.2024.1006 和  6.0.2024.1101  时

redis的连接数发生异常
 5.7.2024.801 三台服务连接数始终稳定在90以内,
6.0.2024.1006 和  6.0.2024.1101 连接数在600以上,

**Comment by microsofter** [comment]
已经收到您的来信，我会尽快回复。

**Comment by xin12023** [comment]
![image](https://github.com/user-attachments/assets/e32ad38a-c2f0-4a30-9757-f893c1aa67f6)
升级前后

**Comment by xin12023** [comment]
![image](https://github.com/user-attachments/assets/7459764e-42f0-4a3e-8a33-d279a28c1d61)
升级前后

**Comment by nnhy** [comment]
这个可能是有bug。新版本取消了同步方法，所有同步调用，都是通过Task.Run包装异步方法。

除了连接数上升，还有其它问题吗？

**Comment by nnhy** [comment]
新版本v6.0的目标是尽可能降低GC，减少内存分配。

**Comment by xin12023** [comment]
因项目使用了sqlsugar 在升级后导致落盘问题,(业务处理中使用了redis锁)
我不能确是因为sqlsugar的问题还是redis锁未升效的问题, 还在测试中
暂时未发现其它问题,

**Comment by nnhy** [comment]
写个控制台项目，跑redis.Bench压测，看看连接数是否大幅上升。这个可以快速判断NewLife.Redis在你的服务器上的兼容性

**Comment by xin12023** [comment]
OK, 我会在找一空闲做出测试,之后再反馈

**Comment by xin12023** [comment]
![image](https://github.com/user-attachments/assets/5b33864a-cfa6-410f-a963-a4b6ba9300df)
这是线上测试降级前后的对比, (未动任何业务代码)
克隆最新源码,运行测试单元 BasicTest(远程redis连接), 出现上涨, 释放后恢复
之后再做更细节 的测试

**Comment by nnhy** [comment]
经本机压测，连接数并没有大增。可参考： https://github.com/NewLifeX/NewLife.Redis/issues/139

![image](https://github.com/user-attachments/assets/c4523a50-c7f3-459f-94d5-ae8049969c4f)

**Comment by nnhy** [comment]
昨晚做了大量测试，压测本机redis时，连接数跟压测线程数相关，64线程有67个连接；
阿里云和腾讯云Redis压测时，连接数的确超过了300个。
注意到，腾讯云Redis有三个Proxy，才到Master/Slave，那么它可能导致连接数多很多。
