### ISSUE TITLE
高并发堵塞

### ISSUE THREAD

**Issue by wild-land** [NewLifeX/NewLife.Redis#139]
项目刚启动完成，我用jmeter 同时并发500线程，redis就会堵塞，当我请求一次后，再执行500压测，就能正常，请问这种情况是什么问题？

**Comment by nnhy** [comment]
使用 v5.x 试试，v6开始做内存优化，修改了底层代码

**Comment by nnhy** [comment]
本机压测，使用64线程时，Redis服务器最高67个连接。测试结束后，连接数自动回收。

![QQ_1732537043148](https://github.com/user-attachments/assets/0b5a07b1-cd5c-4fcf-82a2-2040aed834f0)

**Comment by nnhy** [comment]
捕获上下文做了优化，麻烦重新测试
