### ISSUE TITLE
集群测试异常

### ISSUE THREAD

**Issue by zsy619** [NewLifeX/NewLife.Redis#14]
System.IO.IOException
  HResult=0x80131620
  Message=无法从传输连接中读取数据: 你的主机中的软件中止了一个已建立的连接。。
  Source=System
  StackTrace:
   在 System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   在 System.IO.BufferedStream.ReadByte()
   在 NewLife.Caching.RedisClient.GetResponse(Stream ns, Int32 count)
   在 NewLife.Caching.RedisClient.ExecuteCommand(String cmd, Packet[] args)
   在 NewLife.Caching.RedisClient.Execute(String cmd, Object[] args)
   在 NewLife.Caching.RedisClient.GetInfo()
   在 NewLife.Caching.FullRedis.<>c.<Init>b__11_0(RedisClient r) 在 C:\Users\yangling\Downloads\NewLife.Redis-master\NewLife.Redis-master\NewLife.Redis\FullRedis.cs 中: 第 54 行
   在 NewLife.Caching.Redis.Execute[TResult](String key, Func`2 func, Boolean write)
   在 NewLife.Caching.FullRedis.Execute[T](String key, Func`2 func, Boolean write) 在 C:\Users\yangling\Downloads\NewLife.Redis-master\NewLife.Redis-master\NewLife.Redis\FullRedis.cs 中: 第 78 行
   在 NewLife.Caching.FullRedis.Init(String config) 在 C:\Users\yangling\Downloads\NewLife.Redis-master\NewLife.Redis-master\NewLife.Redis\FullRedis.cs 中: 第 54 行
   在 NewLife.Caching.Redis.Create(String server, Int32 db)
   在 Test.Program.Test6() 在 C:\Users\yangling\Downloads\NewLife.Redis-master\NewLife.Redis-master\Test\Program.cs 中: 第 172 行
   在 Test.Program.Main(String[] args) 在 C:\Users\yangling\Downloads\NewLife.Redis-master\NewLife.Redis-master\Test\Program.cs 中: 第 25 行

内部异常 1:
SocketException: 你的主机中的软件中止了一个已建立的连接。

**Comment by nnhy** [comment]
这个错误信息表示无法从目标主机读取测试。
可以把前面的运行日志贴出来。
集群版Redis启动的时候，会先获取集群数据槽分布信息。

**Comment by nnhy** [comment]
今天在阿里云Redis集群测试通过
