### ISSUE TITLE
docker 环境下，高并发时，大量请求超时

### ISSUE THREAD

**Issue by jason000000001** [NewLifeX/NewLife.Redis#141]
在 Linux docker 环境下大量请求超时 timeout ，本机测试并没有出现这个情况，请问有遇到过吗，应该如何解决，接入的是阿里云的单节点 redis

**Comment by nnhy** [comment]
可以进入容器内部，检查一下到redis的网络是否畅通

**Comment by jason000000001** [comment]
在容器内部访问了redis 网络并没有问题，没什么并发请求的时候。不会出现这个问题。当大量redis操作的时候。就会出现。感觉莫名其妙，之前看到其他人文章有说过是端口开销大。我把 端口已经开到6W5，依然会遇到这个问题。包括Linux内核也处理了

**Comment by nnhy** [comment]
我不熟悉容器，帮不上你太多。
建议你对比容器和虚拟机

**Comment by jason000000001** [comment]
好的，谢谢
