### ISSUE TITLE
集群问题

### ISSUE THREAD

**Issue by wangjunjx8868** [NewLifeX/NewLife.Redis#16]
我在NUGET上引用的不支持集群，但是在GITHUB下载后编译再引用进去就支持集群了，作者你还没有发布到NUGET上吧！

**Comment by nnhy** [comment]
对，还没有发布nuget，增加集群支持以后，还需要等更多人反馈信息。
如果发布了一个不完善的版本上去，那就不好了

**Comment by wangjunjx8868** [comment]
如何使用模糊查询呀？200万数据 set<string>，然后再get精确查询确实快，但是模糊查询有什么好的方案吗？

**Comment by nnhy** [comment]
超过1000数据的查询，建议用SCAN命令，对应FullRedis.Search

**Comment by nnhy** [comment]
在阿里云Redis集群测试通过，预期周末发布nuget

**Comment by zc1185230223** [comment]
集群的有示例demo吗？

**Comment by nnhy** [comment]
自动识别集群，并加载集群配置，不需要专门配置。
只需要连接集群的任意节点即可
