### ISSUE TITLE
List操作实体对象问题

### ISSUE THREAD

**Issue by fymeng2017** [NewLifeX/NewLife.Redis#17]
您好，当操作对象时出现以下错误:
1.
`var listUser = ic.GetList<User>("listAddUser");
            for (int i = 0; i < 10; i++)
            {
                var user = new User { Name = "NewLife_"+i, CreateTime = DateTime.Now };
                listUser.Add(user);
            }`

11:10:54.484  1 N - System.Exception: 不能把字符串[11]转为类型[Test.Program+User] ---> System.InvalidCastException: 从“System.String”到“Test.Program+User”的强制转换无效。
   在 System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   在 System.String.System.IConvertible.ToType(Type type, IFormatProvider provider)
   在 System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   在 System.Convert.ChangeType(Object value, Type conversionType)
   在 NewLife.Reflection.DefaultReflect.ChangeType(Object value, Type conversionType) 位置 D:\X\Src\NewLife.Core\Reflection\IReflect.cs:行号 635

`public void Add(T item) => Execute(r => r.Execute<T>("RPUSH", Key, item), true);`
当Execute<T>改成 Execute<Int32>   可以正确添加

抱歉， 不会添加图片，麻烦帮忙看下！

2.
还有一个问题，第一次获取到数据列表时，如何批量添加到缓存List中,(我想添加到redis中也是list结构，也不是一个json字符串)

**Comment by nnhy** [comment]
NewLife.Core 频繁更新，NewLife.Redis 还没有跟进

**Comment by fymeng2017** [comment]
好的  谢谢

**Comment by nnhy** [comment]
今天更新了，你可以试试

**Comment by wangq2008** [comment]
Json数组无法转为目标类型 仅支持数组和List<T>/IList<T> ，异常报错，尔后用getstring 得到的json用newtonsoft的JsonConvert方法就可以转化为对象。这是怎么回事呢

**Comment by nnhy** [comment]
> Json数组无法转为目标类型 仅支持数组和List/IList ，异常报错，尔后用getstring 得到的json用newtonsoft的JsonConvert方法就可以转化为对象。这是怎么回事呢

这是 rds.Get<T>(key)，这个返回类型T与实际Json不相符，无法转为对象

**Comment by wangq2008** [comment]
如不相符，我用rds.Get<string> 得到json，同样的实例对像用newtonsoft的JsonConvert.DeserializeObject(String)方法就可以正常转化。这就说不过去呀。

**Comment by nnhy** [comment]
> 如不相符，我用rds.Get 得到string json，同样的实例对像用newtonsoft的JsonConvert.DeserializeObject(String)方法就可以正常转化。这就说不过去呀。

可以把json字符串贴出来，以及你的类结构

**Comment by wangq2008** [comment]
[{"Adress":10100,"No":101,"Times":0,"Status":1,"IsSUV":true,"Sort":1,"Index":0,"Disable":false,"IsOut":false},{"Adress":10101,"No":102,"Times":0,"Status":0,"IsSUV":true,"Sort":3,"Index":1,"Disable":false,"IsOut":false},{"Adress":10102,"No":103,"Times":0,"Status":0,"IsSUV":true,"Sort":5,"Index":2,"Disable":false,"IsOut":false},{"Adress":10103,"No":104,"Times":0,"Status":0,"IsSUV":true,"Sort":7,"Index":3,"Disable":false,"IsOut":false},{"Adress":10104,"No":201,"Times":0,"Status":0,"IsSUV":true,"Sort":2,"Index":4,"Disable":false,"IsOut":true},{"Adress":10105,"No":202,"Times":0,"Status":0,"IsSUV":true,"Sort":4,"Index":5,"Disable":false,"IsOut":true},{"Adress":10106,"No":203,"Times":0,"Status":0,"IsSUV":true,"Sort":6,"Index":6,"Disable":false,"IsOut":true},{"Adress":10107,"No":204,"Times":0,"Status":0,"IsSUV":true,"Sort":8,"Index":7,"Disable":false,"IsOut":true},{"Adress":10108,"No":105,"Times":0,"Status":0,"IsSUV":false,"Sort":9,"Index":8,"Disable":false,"IsOut":false},{"Adress":10109,"No":106,"Times":0,"Status":0,"IsSUV":false,"Sort":11,"Index":9,"Disable":false,"IsOut":false},{"Adress":10110,"No":107,"Times":0,"Status":0,"IsSUV":false,"Sort":13,"Index":10,"Disable":false,"IsOut":false},{"Adress":10111,"No":108,"Times":0,"Status":0,"IsSUV":false,"Sort":15,"Index":11,"Disable":false,"IsOut":false},{"Adress":10112,"No":109,"Times":0,"Status":0,"IsSUV":false,"Sort":17,"Index":12,"Disable":false,"IsOut":false},{"Adress":10113,"No":110,"Times":0,"Status":0,"IsSUV":false,"Sort":19,"Index":13,"Disable":false,"IsOut":false},{"Adress":10114,"No":111,"Times":0,"Status":0,"IsSUV":false,"Sort":21,"Index":14,"Disable":false,"IsOut":false},{"Adress":10115,"No":112,"Times":0,"Status":0,"IsSUV":false,"Sort":23,"Index":15,"Disable":false,"IsOut":false},{"Adress":10116,"No":113,"Times":0,"Status":0,"IsSUV":false,"Sort":25,"Index":16,"Disable":false,"IsOut":false},{"Adress":10117,"No":114,"Times":0,"Status":1,"IsSUV":false,"Sort":27,"Index":17,"Disable":false,"IsOut":false},{"Adress":10118,"No":115,"Times":0,"Status":1,"IsSUV":false,"Sort":29,"Index":18,"Disable":false,"IsOut":false},{"Adress":10119,"No":116,"Times":0,"Status":0,"IsSUV":false,"Sort":31,"Index":19,"Disable":false,"IsOut":false},{"Adress":10120,"No":117,"Times":0,"Status":0,"IsSUV":false,"Sort":33,"Index":20,"Disable":false,"IsOut":false},{"Adress":10121,"No":118,"Times":0,"Status":0,"IsSUV":false,"Sort":35,"Index":21,"Disable":false,"IsOut":false},{"Adress":10122,"No":205,"Times":0,"Status":1,"IsSUV":false,"Sort":10,"Index":22,"Disable":false,"IsOut":true},{"Adress":10123,"No":206,"Times":0,"Status":0,"IsSUV":false,"Sort":12,"Index":23,"Disable":false,"IsOut":true},{"Adress":10124,"No":207,"Times":0,"Status":1,"IsSUV":false,"Sort":14,"Index":24,"Disable":false,"IsOut":true},{"Adress":10125,"No":208,"Times":0,"Status":0,"IsSUV":false,"Sort":16,"Index":25,"Disable":false,"IsOut":true},{"Adress":10126,"No":209,"Times":0,"Status":0,"IsSUV":false,"Sort":18,"Index":26,"Disable":false,"IsOut":true},{"Adress":10127,"No":210,"Times":0,"Status":0,"IsSUV":false,"Sort":20,"Index":27,"Disable":false,"IsOut":true},{"Adress":10128,"No":211,"Times":0,"Status":0,"IsSUV":false,"Sort":22,"Index":28,"Disable":false,"IsOut":true},{"Adress":10129,"No":212,"Times":0,"Status":0,"IsSUV":false,"Sort":24,"Index":29,"Disable":false,"IsOut":true},{"Adress":10130,"No":213,"Times":0,"Status":0,"IsSUV":false,"Sort":26,"Index":30,"Disable":false,"IsOut":true},{"Adress":10131,"No":214,"Times":0,"Status":0,"IsSUV":false,"Sort":28,"Index":31,"Disable":false,"IsOut":true},{"Adress":10132,"No":215,"Times":0,"Status":0,"IsSUV":false,"Sort":30,"Index":32,"Disable":false,"IsOut":true},{"Adress":10133,"No":216,"Times":0,"Status":0,"IsSUV":false,"Sort":32,"Index":33,"Disable":false,"IsOut":true},{"Adress":10134,"No":217,"Times":0,"Status":0,"IsSUV":false,"Sort":34,"Index":34,"Disable":false,"IsOut":true},{"Adress":10135,"No":218,"Times":0,"Status":0,"IsSUV":false,"Sort":36,"Index":35,"Disable":false,"IsOut":true}]

//
 public  class LocationEntity
    {
        /// <summary>
        /// PLC D区地址
        /// </summary>
        public short Adress { set; get; }
        /// <summary>
        /// 车位号
        /// </summary>
        public int No { set; get; }
        /// <summary>
        /// 存放次数
        /// </summary>
        public int Times { set; get; }
        /// <summary>
        /// 车位状态
        /// </summary>
        public int Status { set; get; }
        public bool IsSUV { set; get; }
        /// <summary>
        /// 排序，低由高
        /// </summary>
        public int Sort { set; get; }
        public int Index { set; get; }
        /// <summary>
        /// 是否启用
        /// </summary>
        public bool Disable { set; get; }
        /// <summary>
        /// 是否是出口
        /// </summary>
        public bool IsOut { set; get; }
    }

**Comment by nnhy** [comment]
var arr = rds.Get<LocationEntity[]>(key)

**Comment by wangq2008** [comment]
哦，这样 Get<T> T如是集合只能是数组，不能为List是吗？因为我存的时候就是List<T>类型，所以我取的时候也是用Get<List<T>>,所以就报错了

**Comment by nnhy** [comment]
> 哦，这样 Get T如是集合只能是数组，不能为List是吗？因为我存的时候就是List类型，所以我取的时候也是用Get<List>,所以就报错了

你说的的确可能是一个兼容性问题，平时都用数组所以没有太多注意，底层json序列化用的是精简版快速Json，不具备完整Json功能。
另外，你也可以重载Redis类，覆盖相应方法。

**Comment by nnhy** [comment]
> 哦，这样 Get T如是集合只能是数组，不能为List是吗？因为我存的时候就是List类型，所以我取的时候也是用Get<List>,所以就报错了

已确认这是底层NewLife.Core内的json序列化BUG，已修正！

**Comment by 840900649** [comment]
我也发现这问题，并已经昨天更新代码。但无效果， 还是需要将Execute<T> 改为 Execute

**Comment by nnhy** [comment]
Execute 改为 Execute ？？

**Comment by 840900649** [comment]
Execute<T> 改为 Execute，

**Comment by 840900649** [comment]
Execute{T} 改为 Execute，没

**Comment by nnhy** [comment]
List.Add的返回类型有BUG，已修正！

https://github.com/NewLifeX/NewLife.Redis/commit/445b1c8501bfaadb0d22ea10154b4dac5285f597
