### ISSUE TITLE
更新NewLife.Core至8.0.6965.42074后   NewLife.Redis  List添加时报错

### ISSUE THREAD

**Issue by q1a0mu** [NewLifeX/NewLife.Redis#18]
var list = ic.GetList<DateTime>("list");
list.Add(DateTime.Now); //执行到这一句出现异常 8.0.6940.24647版本没有问题

23:49:03.349  1 N - System.MissingMethodException: 找不到方法:“System.DateTime NewLife.Caching.Redis.Execute(System.Func`2<NewLife.Caching.RedisClient,System.DateTime>, Boolean)”。
   在 NewLife.Caching.RedisBase.Execute[T](Func`2 func, Boolean write)
   在 NewLife.Caching.RedisList`1.Add(T item) 位置 D:\X\NewLife.Redis\NewLife.Redis\RedisList.cs:行号 39
   在 NewLifeRedisDemo.Program.Main(String[] args) 位置

**Comment by nnhy** [comment]
版本兼容问题，按照计划，这个周末会进行代码合并，以及nuget发布

**Comment by nnhy** [comment]
今天更新了版本
