### ISSUE TITLE
偶发内存溢出问题，测试一个key存放10W以内的集合没有问题

### ISSUE THREAD

**Issue by Gavin-Peking** [NewLifeX/NewLife.Redis#19]
部分源码：
`
ICollection<string> set = RedisHelper.Instance.GetSet<string>("KF_" + productCode); 
 if (set.Count == 0)         {        
     List<RapidPublishEntity> list4 = this._RapidPublishRepository.SelectByProCode(productCode);             
     foreach (RapidPublishEntity entity3 in list4)  
           {                
                    set.Add(string.Concat(new object[] { (int) entity3.CategoryType, "_", entity3.TagCode, "_", entity3.UrlID }));    
         }   
      }
`

--
`
public class RedisHelper {  
    private static Redis redis; 
    static RedisHelper()     {    
               FullRedis.Register();
               string environmentVariable = Environment.GetEnvironmentVariable("REDIS_DB_SETTING", EnvironmentVariableTarget.Machine); 
              int db = string.IsNullOrEmpty(environmentVariable) ? 0 : Convert.ToInt32(environmentVariable);         
              redis = Redis.Create("192.168.106.56:6379", db);     }  
    private RedisHelper()     { }    
  public static Redis Instance     {         get         {             return redis;         }     } }
`
--

事件查看器提示：
Message: 引发类型为“System.OutOfMemoryException”的异常。

StackTrace:    在 System.Text.StringBuilder.ToString()
   在 NewLife.Collections.Pool.Put(StringBuilder sb, Boolean requireResult) 位置 D:\X\Src\NewLife.Core\Collections\IPool.cs:行号 44
   在 System.StringHelper.Join[T](IEnumerable`1 value, String separator, Func`2 func) 位置 D:\X\Src\NewLife.Core\Extension\StringHelper.cs:行号 271
   在 System.DefaultConvert.GetMessage(Exception ex) 位置 D:\X\Src\NewLife.Core\Common\Utility.cs:行号 472
   在 NewLife.Log.WriteLogEventArgs.ToString() 位置 D:\X\Src\NewLife.Core\Log\WriteLogEventArgs.cs:行号 100
   在 NewLife.Log.TextFileLog.OnWrite(LogLevel level, String format, Object[] args) 位置 D:\X\Src\NewLife.Core\Log\TextFileLog.cs:行号 251
   在 NewLife.Log.Logger.Write(LogLevel level, String format, Object[] args) 位置 D:\X\Src\NewLife.Core\Log\Logger.cs:行号 48
   在 NewLife.Log.Logger.Error(String format, Object[] args) 位置 D:\X\Src\NewLife.Core\Log\Logger.cs:行号 33
   在 NewLife.Log.XTrace.WriteException(Exception ex) 位置 D:\X\Src\NewLife.Core\Log\XTrace.cs:行号 62
   在 NewLife.Threading.ThreadPoolX.<>c__DisplayClass2_0.<QueueUserWorkItem>b__0(Object s) 位置 D:\X\Src\NewLife.Core\Threading\ThreadPoolX.cs:行号 40
   在 System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   在 System.Threading.ThreadPoolWorkQueue.Dispatch()
   在 System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by Gavin-Peking** [comment]
[Redis 使用问题描述.txt](https://github.com/NewLifeX/NewLife.Redis/files/2939947/Redis.txt)

**Comment by nnhy** [comment]
rds.Log = XTrace.Log
打开日志，可以看到具体操作

**Comment by Gavin-Peking** [comment]
> rds.Log = XTrace.Log
> 打开日志，可以看到具体操作

好的，我去试一下，谢
