### ISSUE TITLE
redis操作都是异步的吗, 还是说区分异步同步接口, 支持await吗

### ISSUE THREAD

**Issue by swpuzhang** [NewLifeX/NewLife.Redis#20]

**Comment by nnhy** [comment]
redis操作都是同步，不支持异步！
NewLife.Redis特别为大数据实时计算进行优化，需要超低延迟（0.2~0.6ms），超高性能（10万~200万ops）。
经过测试，异步比同步并没有优势，甚至高并发时比同步略慢。
通过get/set目标数据，只需要小于200us的延迟，这个时候异步操作导致线程切换所带来损耗，相比之下已经比较可观。
