### ISSUE TITLE
redis连接池的连接部分不会自动回收

### ISSUE THREAD

**Issue by xueandfeng** [NewLifeX/NewLife.Redis#21]
我想自己控制线程池的最大最小值

**Comment by nnhy** [comment]
NewLife.Redis没有使用线程池，同步架构！
X组件大部分场景使用了系统线程池。

NewLife.Redis内部使用了连接池，每个池默认最大1000个连接。

**Comment by xueandfeng** [comment]
那NewLife.Redis内部的连接池中的连接，长时间未使用的情况会回收吗。

**Comment by nnhy** [comment]
回收的，空闲60秒还是120秒，忘记了

**Comment by xueandfeng** [comment]
好的。我在看看。我的不知道咋回事。长时间空闲。连接不回收。
有没有可能是我通过DI注入的方式是单例原因？

**Comment by nnhy** [comment]
Redis本来就应该是单例使用，你观察一下，120秒以后还有多少个连接

**Comment by xueandfeng** [comment]
就是看到连接只有新增。没有减少。开启日志也是没有看到日志回收工作的日志以下地址
https://github.com/NewLifeX/X/blob/master/NewLife.Core/Collections/ObjectPool.cs#L362

**Comment by nnhy** [comment]
那个日志需要修改日志级别，配置文件config/core.config，Debug=true，LogLevel=All

**Comment by xueandfeng** [comment]
![图片](https://user-images.githubusercontent.com/20178645/55273588-72a88000-5308-11e9-9dbb-8d4d65e82676.png)
日志配的是ALL 。
![图片](https://user-images.githubusercontent.com/20178645/55273610-adaab380-5308-11e9-994f-bd8991390eaf.png)
然后就没有日志了

**Comment by xueandfeng** [comment]
https://github.com/NewLifeX/X/blob/master/NewLife.Core/Collections/ObjectPool.cs#L312
我这边debug是看这里进行移除了。但是连接没有被回收。
![图片](https://user-images.githubusercontent.com/20178645/55275257-76470180-531e-11e9-93d2-92fef0d77774.png)
最底下没办法进行释放

**Comment by xueandfeng** [comment]
我的问题。我用到了自动管道(AutoPipeline=1)后,最后没调用Commit()方法导致的

**Comment by nnhy** [comment]
哈哈！尴尬了，我没想到这一层
