### ISSUE TITLE
GetDictionary<T>(key).TryGetValue  NullReferenceException: 未将对象引用设置到对象的实例

### ISSUE THREAD

**Issue by vfeihuang** [NewLifeX/NewLife.Redis#22]
辅助类定义
 private static RedisConfig redisConfig = RedisConfig.GetConfig(); 
        private static Redis Core { get; set; }
        public NewLifeRedis(int dbIndex = 0) {
            if (Core == null) { 
                FullRedis.Register(); 
                Core = Redis.Create(redisConfig.ServerConStr, dbIndex); 
            }
        }
        public T Hash_Get<T>(string key, long dataKey) {
            //try {
                T t;
                Core.GetDictionary<T>(key).TryGetValue(dataKey.ToString(), out t);
                return t;
            //}
            //catch (Exception ex) {
            //    return default(T);
            //}
        }
}
调用：
var m = cache.Hash_Get<Class.Dic_mdxx_cmpy>(key, mdid);
问题：
当hash集合key中不存在键为dataKey的值时，会报空指针错误

行 210:            //try {
行 211:                T t;
行 212:                Core.GetDictionary<T>(key).TryGetValue(dataKey.ToString(), out t);
行 213:                return t;
行 214:            //}

[NullReferenceException: 未将对象引用设置到对象的实例。]
   NewLife.Caching.RedisHash`2.TryGetValue(TKey key, TValue& value) +125
   Cacher.NewLifeRedis.Hash_Get(String key, Int64 dataKey) in d:\Project\2013\xxxxx\Cacher\NewLifeRedis.cs:212

所以需要 加上 try{}catch{} ，请问TryGetValue方法内是不是可以再处理下

这是直接使用命令行返回的值

172.16.1.144:0>HGET smls_md  487
null

**Comment by nnhy** [comment]
TryGetValue函数写得不好，可以直接用字典的索引器来获取

**Comment by nnhy** [comment]
修正RedisHash.TryGetValue空引用异常 · NewLifeX/NewLife.Redis@8889f3c
https://github.com/NewLifeX/NewLife.Redis/commit/8889f3c99cf97fb2c97ea27f286fa2f06cfde5c7
