### ISSUE TITLE
ERR wrong number of arguments for 'setnx' command

### ISSUE THREAD

**Issue by yaoyuansheng** [NewLifeX/NewLife.Redis#23]
执行_redis.Add(cacheKey, DateTime.Now, second) 会提示ERR wrong number of arguments for 'setnx' command   redis版本3.2
在客户端执行
![image](https://user-images.githubusercontent.com/13847155/56796782-dc537580-6845-11e9-91fa-53fac8bf2562.png) 倒没问题

**Comment by xxred** [comment]
旧版本的setnx不支持设置过期时间
后续修复。

**Comment by nnhy** [comment]
问题已修复！可以测试一下。

https://github.com/NewLifeX/X/commit/8bcde9f5821eb9429f716c626661e2e1b46876af

**Comment by nnhy** [comment]
最新的0701版本已支持智能识别，低于3.2的redis将自动拆分为两条命令
