### ISSUE TITLE
提示 《键名》的元素个数过多，不支持遍历！

### ISSUE THREAD

**Issue by niunan** [NewLifeX/NewLife.Redis#24]
刚刚在项目中用了。。本地还好，传上网出问题。。
我读 的是hash里的所有东西。。。

提示 《键名》的元素个数过多，不支持遍历！

是不是数量过多就不让遍历啊。。

**Comment by nnhy** [comment]
是的，故意限制！
Redis中使用Keys本来就是大忌，所以Redis类里面限制10000元素以上禁止使用Keys
你可以改用 FullRedis.Search 方法进行匹配和分页

`
        /// <summary>所有键</summary>
        public override ICollection<String> Keys
        {
            get
            {
                if (Count > 10000) throw new InvalidOperationException("数量过大时，禁止获取所有键");

                var client = Pool.Get();
                try
                {
                    var rs = client.Execute<String[]>("KEYS", "*");
                    //return rs.Split(Environment.NewLine).ToList();
                    return rs;
                }
                finally
                {
                    Pool.Put(client);
                }
            }
        }
`
