### ISSUE TITLE
希望增加一个 List 的AddRange 方法和快速对比方法

### ISSUE THREAD

**Issue by 840900649** [NewLifeX/NewLife.Redis#25]
目前List Add 较慢，当前解决方法是使用自带管道 写了个批量添加速度提升数十倍。
目前实用where 查询 一个月给遍历。速度很慢，试过join 也比较慢。 有什么通过id 快速对比的方法最好。

**Comment by nnhy** [comment]
添加 RedisList.AddRange，支持批量添加元素到列表 · NewLifeX/NewLife.Redis@65e5308
https://github.com/NewLifeX/NewLife.Redis/commit/65e53083b883bcad197e07fe25b9db0d3fb4efd9
