### ISSUE TITLE
List 无法进行 Clear 清空

### ISSUE THREAD

**Issue by 840900649** [NewLifeX/NewLife.Redis#26]
最新版本、清空list 无效。之前版本也出现这个情况。 
清空代码：
           var ic = Redis.Create("127.0.0.1:6379", 3);
            ic.Log = XTrace.Log;
            var list=(RedisList<int>)ic.GetList<int>("tetst_int");
            List<int> ls = new List<int>();
            for (int i = 0; i < 1000; i++)
            {
                ls.Add(i);
            }
            list.AddRange(ls);
            list.Clear();
            Console.WriteLine(list.Count);

**Comment by 840900649** [comment]
解决方案：RedisList 类下的 
 
    public void Clear() => LTrim(0, -1);
改为
    public void Clear() => LTrim(-1, 0);

**Comment by nnhy** [comment]
这个问题，几个月之前已修改
