### ISSUE TITLE
NewLife.Redis设置DB后。重启redis服务后失效

### ISSUE THREAD

**Issue by xueandfeng** [NewLifeX/NewLife.Redis#29]
使用NewLife.Redis设置好DB=1后进行连接redis服务端后。进行redis服务端进行重启。
NewLife.Redis的DB默认为0了。缓存全部进入DB为0的下面了

![图片](https://user-images.githubusercontent.com/20178645/59243111-eb995180-8c40-11e9-977f-776da8c56374.png)

![图片](https://user-images.githubusercontent.com/20178645/59243173-30bd8380-8c41-11e9-8b41-32b1b148774a.png)

**Comment by xueandfeng** [comment]
NewLife.Redis 版本 3.1.2019.513

**Comment by nnhy** [comment]
改问题已修正！本地模拟服务器重启，测试通过。

RedisClient网络重连时，除了重新验证密码外，还要选择数据库 · NewLifeX/X@2fdbc3f
https://github.com/NewLifeX/X/commit/2fdbc3fafb814a368c9e1d39186ac273b94947be

**Comment by xueandfeng** [comment]
nuget上更新下呗

**Comment by nnhy** [comment]
nuget按计划大概15~20天更新一次，今天刚刚安排发布更新，稍候你可以拿到0618最新版
