### ISSUE TITLE
使用使用set方法存储对象，出现异常问题。

### ISSUE THREAD

**Issue by BootsShu** [NewLifeX/NewLife.Redis#30]
具体情况描述：
      使用NewLife.Redis，set方法，存储对象至redis中，发现存储至redis的这个对象中list数据类型的成员全部丢失了。
    
   调用方法：_client.Set<T>(key, value, expire);
   RedisValue数据类型：

    public class RoleMenuOperationRelationInRedisDto
    {
       
        public long UserId { get; set; }
        public ApplyInRedisDto Apply { get; set; }

        public List<MenuInRedisDto> Menus = new List<MenuInRedisDto>();
        public List<OperationInRedisDto> Operations = new List<OperationInRedisDto>();
    }

    public class MenuInRedisDto
    {
        public int ApplyId { get; set; }

        public string MenuUrl { get; set; }

        public string MenuName { get; set; }

        public string MenuDesc { get; set; }
    }

    public class OperationInRedisDto
    {
        public string ActionUrl { get; set; }

        public string ActionName { get; set; }

        public string ActionDesc { get; set; }
    }

**Comment by xxred** [comment]
麻烦提供下完整的能跑的代码，以及执行过程的相关信息，是否有报错等

**Comment by xxred** [comment]
或者，这种复杂对象先序列化成字符串再存取

**Comment by BootsShu** [comment]
> 麻烦提供下完整的能跑的代码，以及执行过程的相关信息，是否有报错等

当然可以。

链接：https://pan.baidu.com/s/1BdBnZjMdTTd75ZplhpRtuA 
提取码：66h1 
复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by BootsShu** [comment]
> 或者，这种复杂对象先序列化成字符串再存取

请问，NewLife.Redis，会考虑在底层修复不支持复杂数据类型的问题吗？

**Comment by xxred** [comment]
@BootsShu 就是通过json序列化支持的
参考 https://www.newlifex.com/Redis/#%E4%BF%9D%E5%AD%98%E5%AF%B9%E8%B1%A1

**Comment by nnhy** [comment]
rds.Set(key, value)，其中value如果是复杂对象，会进行json序列化处理；
同理，读取的时候，返回值也会进行json反序列化处理；
因此，如果rds.Get<String>(key)，那么可以得到写入redis的字符串是什么，赶在json反序列化之前，这样方便你查找问题所在。

另外，rds.Log=XTrace.Log 打开日志，可以看到跟redis交互的每一次指令，其中可以发现一些问题。
