### ISSUE TITLE
建议将所有配置改成可自定义

### ISSUE THREAD

**Issue by 840900649** [NewLifeX/NewLife.Redis#31]
如 XmlConfigFile，类。只需要给一个配置名：CoreConfig, 会自动IOC容器里找，没找到的话默认 使用路径： Config\Core.config。 这样就可以最大的保持代码的高自由了。

**Comment by nnhy** [comment]
有没有更详细一些的想法？

**Comment by 840900649** [comment]
在需要配置得地方多加一个参数：配置名称, 形成（[XmlConfigFile("CoreConfig"，@"Config\Core.config", 15000)]）;然后再增加一个IOC 容器， 可以像容器里注入自己的配置和获取配置：
AddConfigPath(string configName,string configPath){
}
GetConfigPath(string configName){


}
XmlConfigFile 只需要根据自己的配置名称（CoreConfig）去调用GetXmlConfig即可。
同样，日志文件也可以这样读取（约定名称，LogOutPath)






------------------ 原始邮件 ------------------
发件人: "Stone"<notifications@github.com>; 
发送时间: 2019年7月8日(星期一) 上午10:44
收件人: "NewLifeX/NewLife.Redis"<NewLife.Redis@noreply.github.com>; 
抄送: "情至深时人孤独"<840900649@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [NewLifeX/NewLife.Redis] 建议将所有配置改成可自定义 (#31)




有没有更详细一些的想法？

**Comment by 840900649** [comment]
或者全放在Setting里面也行，




------------------ 原始邮件 ------------------
发件人: "我自己的邮箱"<840900649@qq.com>;
发送时间: 2019年7月8日(星期一) 上午10:52
收件人: "NewLifeX/NewLife.Redis"<reply@reply.github.com>;"NewLifeX/NewLife.Redis"<NewLife.Redis@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;
主题: 回复： [NewLifeX/NewLife.Redis] 建议将所有配置改成可自定义 (#31)



 然后再增加一个IOC 容器， 可以像容器里注入自己的配置和获取配置：
AddConfigPath(string configName,string configPath){
}
GetConfigPath(string configName){


}
XmlConfigFile 只需要根据自己的配置名称（CoreConfig）去调用GetXmlConfig即可。
同样，日志文件也可以这样读取（约定名称，LogOutPath)






------------------ 原始邮件 ------------------
发件人: "Stone"<notifications@github.com>; 
发送时间: 2019年7月8日(星期一) 上午10:44
收件人: "NewLifeX/NewLife.Redis"<NewLife.Redis@noreply.github.com>; 
抄送: "情至深时人孤独"<840900649@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [NewLifeX/NewLife.Redis] 建议将所有配置改成可自定义 (#31)




有没有更详细一些的想法？

**Comment by nnhy** [comment]
这个是将来核心库配置模块的一个改造方向，现在还不支持

**Comment by nnhy** [comment]
核心库配置模块在今年初已经重构，支持xml/json/ini，从实际使用情况来看，大部分还是使用xml，因为它能够很友好的支持注释，而json在注释支持上很弱
