### ISSUE TITLE
docker环境下NewLife.Net.NetUri.Parse解析问题

### ISSUE THREAD

**Issue by xueandfeng** [NewLifeX/NewLife.Redis#32]
这2个地方能改成我下面数组分割的方式吗.
![image](https://user-images.githubusercontent.com/20178645/62203532-f3ae7b80-b3bd-11e9-8d60-0a3463079eb8.png)
![image](https://user-images.githubusercontent.com/20178645/62203550-fe691080-b3bd-11e9-8412-4377a7b02855.png)
因为最近我的项目是多语言功能（中,英,泰）
使用的是ASP.NET Core 全球化和本地化(https://docs.microsoft.com/zh-cn/aspnet/core/fundamentals/localization?view=aspnetcore-2.2)
然后发现部署在docker下的时候。中文和英文请求NewLife.Redis是连接正常的没有问题.
当是泰语的时候发现
https://github.com/NewLifeX/X/blob/master/NewLife.Core/Net/NetUri.cs#L138
https://github.com/NewLifeX/X/blob/master/NewLife.Core/Net/NetUri.cs#L168
IndexOf和LastIndexOf返回的位置居然是0
![image](https://user-images.githubusercontent.com/20178645/62203974-d29a5a80-b3be-11e9-9cd0-25ef1140225a.png)

**Comment by nnhy** [comment]
这个反馈很好，可以修改后直接提交PR。
X组件没有测试过中英文以外的语言。
