### ISSUE TITLE
请问发布订阅是不是还没整好？

### ISSUE THREAD

**Issue by christan-duplicate** [NewLifeX/NewLife.Redis#33]
请问发布订阅是不是还没整好？

**Comment by nnhy** [comment]
对，发布订阅还是没有经过测试，只是写了代码。
我们实际使用更多倾向于LIST的拉取消费

**Comment by nnhy** [comment]
推荐使用 FullRedis.GetQueue，采取消费端拉取的方式。这个队列经过了严密测试，也支持ACK，但是不支持多消费组。
最新的redis5.0新增了Stream，专用于消息队列，支持多消费组，目前正在封装测试，预计8月初的newlife.redis正式版中可以跟大家见面。
