### ISSUE TITLE
这个应该要更新一下了，不能适配最新的NewLife.Core了。

### ISSUE THREAD

**Issue by qcjxberin** [NewLifeX/NewLife.Redis#35]
![image](https://user-images.githubusercontent.com/5792218/68993459-6c750d00-08b3-11ea-8ac7-0bdf27befb3a.png)

**Comment by nnhy** [comment]
问题已解决！
已更新源码组件，已发布nuget1117

**Comment by qcjxberin** [comment]
感谢
