### ISSUE TITLE
请问有同步异步的示例代码吗

### ISSUE THREAD

**Issue by orangeagain** [NewLifeX/NewLife.Redis#36]
请问所有的方法都是线程安全吗？

**Comment by nnhy** [comment]
Redis所有方法都是线程安全的

**Comment by nnhy** [comment]
在实际应用中，日均100亿次调用，平均延迟100~600us，非常低，Bench并发100万tps以上，已经没有修改为异步的必要。
也尝试过几次异步，测试吞吐率并没有改变，延迟反而加大了。

**Comment by orangeagain** [comment]
> 在实际应用中，日均100亿次调用，平均延迟100~600us，非常低，Bench并发100万tps以上，已经没有修改为异步的必要。
> 也尝试过几次异步，测试吞吐率并没有改变，延迟反而加大了。

好的，学到了
