### ISSUE TITLE
怎样自定义json序列化

### ISSUE THREAD

**Issue by orangeagain** [NewLifeX/NewLife.Redis#37]
这个库确实很快，但是我发现使用utf8json这个库可以使json序列化性能提高5倍,所以我想换一个序列化库。

如果redis的value是二进制的话，换一个序列化库是很简单的

**Comment by nnhy** [comment]
继承 RedisClient，重写转换函数

**Comment by orangeagain** [comment]
`
开始
=====================原生序列化Set======================
预热533.231
401.1273
382.95500000000004
375.0294
Avg:386.37056666666666
=====================ToJson序列化Set=====================
344.23670000000004
440.4613
385.2541
Avg:389.98403333333334
=====================JsonHelper.ToJson序列化Set=====================
368.3168
390.6643
379.7808
Avg:379.58729999999997
=====================UTF8Json.ToJsonString序列化Set=====================
预热:748.8747000000001
286.6234
291.8512
280.4226
Avg:286.29906666666665
=====================UTF8Json.ToBytes序列化Set=====================
284.8295
286.1154
281.165
Avg:284.0366333333333
=====================反序列化===================
=====================原生反序列化Get=====================
339.3693
312.86670000000004
316.4152
Avg:322.8837333333334
=====================JsonHelper反序列化Get=====================
299.7129
302.4057
298.3494
Avg:300.156
=====================Utf8JsonString反序列化Get=====================
367.48400000000004
280.2508
281.8875
Avg:309.8741
=====================Utf8JsonBytes反序列化Get=====================
283.7594
271.6941
281.3508
Avg:278.9347666666667
`

可以看出用Utf8Json.Bytes最快

**Comment by nnhy** [comment]
非常给力！
