### ISSUE TITLE
源码运行报错

### ISSUE THREAD

**Issue by hufei008** [NewLifeX/NewLife.Redis#39]
09:40:01.839  1 N - => OK
09:40:01.841  1 N - GET time
09:40:01.842  1 N - => 2019-11-29 09:40:01
2019-11-29 09:40:01
09:40:02.946  1 N - GET time
09:40:02.975  1 N - GET time
09:40:02.977  1 N - GET time
09:40:02.977  1 N - GET time
09:40:03.019  1 N - System.IO.InvalidDataException: 解码时找到无效数据。
   在 NewLife.Caching.RedisClient.ReadPacket(Stream ms) 位置 D:\X\Src\NewLife.Core\Caching\RedisClient.cs:行号 343
   在 NewLife.Caching.RedisClient.ReadBlock(Stream ms) 位置 D:\X\Src\NewLife.Core\Caching\RedisClient.cs:行号 302
   在 NewLife.Caching.RedisClient.GetResponse(Stream ns, Int32 count) 位置 D:\X\Src\NewLife.Core\Caching\RedisClient.cs:行号 210
   在 NewLife.Caching.RedisClient.ExecuteCommand(String cmd, Packet[] args) 位置 D:\X\Src\NewLife.Core\Caching\RedisClient.cs:行号 253
   在 NewLife.Caching.RedisClient.Execute(String cmd, Object[] args) 位置 D:\X\Src\NewLife.Core\Caching\RedisClient.cs: 行号 390
   在 NewLife.Caching.RedisClient.Execute[TResult](String cmd, Object[] args) 位置 D:\X\Src\NewLife.Core\Caching\RedisClient.cs:行号 405
   在 NewLife.Caching.Redis.<>c__DisplayClass56_0`1.<Get>b__0(RedisClient rds) 位置 D:\X\Src\NewLife.Core\Caching\Redis.cs:行号 406
   在 NewLife.Caching.Redis.Execute[TResult](String key, Func`2 func, Boolean write) 位置 D:\X\Src\NewLife.Core\Caching\Redis.cs:行号 280
   在 NewLife.Caching.FullRedis.Execute[T](String key, Func`2 func, Boolean write)
   在 NewLife.Caching.Redis.Get[T](String key) 位置 D:\X\Src\NewLife.Core\Caching\Redis.cs:行号 406
   在 Test.Program.Test1() 位置 D:\360安全浏览器下载\NewLife.Redis-master\Test\Program.cs:行号 55
   在 Test.Program.Main(String[] args) 位置 D:\360安全浏览器下载\NewLife.Redis-master\Test\Program.cs:行号 25
09:40:06.832  7 Y T FullRedisPool.Release New=1 Release=0 Free=1 Busy=0 清除过期资源 0 项。总请求 12 次，命中 91.67%，平均 3,982.15us

**Comment by nnhy** [comment]
实际上存了什么数据进去？

**Comment by hufei008** [comment]
就运行下载的源码，我自己没存东西

**Comment by nnhy** [comment]
用的是Windows Redis吗？注意版本不能太老

**Comment by hufei008** [comment]
用的是这个Redis-x64-3.2.100.msi

**Comment by nnhy** [comment]
这个错误是偶发性还是每次都能重现？
我们在高频读写（10w+ tps）时会有一定几率遇到这个错误

**Comment by hufei008** [comment]
每次都会出现，
ic.Set("time", DateTime.Now, 1);
 Console.WriteLine(ic.Get<DateTime>("time").ToFullString());
Thread.Sleep(1100);
//Console.WriteLine(ic.Get<DateTime>("time").ToFullString());
我把 这行注释掉就能运行 Test1()这个方法， 不知道会不会是redis版本问题，好像是这个key 过期了就读不了报异常了

**Comment by nnhy** [comment]
已确认为Redis高速管道模式BUG，不影响日常使用，已修正！
https://github.com/NewLifeX/X/commit/322e737629ebdb8c1ec7dba7e27ba9468db52324
