### ISSUE TITLE
源码性能压力测试报错了

### ISSUE THREAD

**Issue by hufei008** [NewLifeX/NewLife.Redis#40]
09:43:33.637  1 N - 为NewLife.Caching.Redis自动注册NewLife.Caching.FullRedis
09:43:33.642  1 N - 目标服务器：127.0.0.1/3
09:43:33.643  1 N - FullRedis性能测试[随机]，批大小[100]，逻辑处理器 8 个
09:43:33.644  1 N -
09:43:33.645  1 N - 测试 100,000 项，  1 线程
09:43:33.831  1 N - System.IO.InvalidDataException: 解码时找到无效数据。
   在 NewLife.Caching.RedisClient.ReadPacket(Stream ms) 位置 D:\X\Src\NewLife.Core\Caching\RedisClient.cs:行号 343
   在 NewLife.Caching.RedisClient.ReadBlock(Stream ms) 位置 D:\X\Src\NewLife.Core\Caching\RedisClient.cs:行号 302
   在 NewLife.Caching.RedisClient.GetResponse(Stream ns, Int32 count) 位置 D:\X\Src\NewLife.Core\Caching\RedisClient.cs:行号 210
   在 NewLife.Caching.RedisClient.ExecuteCommand(String cmd, Packet[] args) 位置 D:\X\Src\NewLife.Core\Caching\RedisClient.cs:行号 253
   在 NewLife.Caching.RedisClient.Execute(String cmd, Object[] args) 位置 D:\X\Src\NewLife.Core\Caching\RedisClient.cs: 行号 390
   在 NewLife.Caching.RedisClient.Execute[TResult](String cmd, Object[] args) 位置 D:\X\Src\NewLife.Core\Caching\RedisClient.cs:行号 405
   在 NewLife.Caching.Redis.<>c__DisplayClass56_0`1.<Get>b__0(RedisClient rds) 位置 D:\X\Src\NewLife.Core\Caching\Redis.cs:行号 406
   在 NewLife.Caching.Redis.Execute[TResult](String key, Func`2 func, Boolean write) 位置 D:\X\Src\NewLife.Core\Caching\Redis.cs:行号 280
   在 NewLife.Caching.FullRedis.Execute[T](String key, Func`2 func, Boolean write)
   在 NewLife.Caching.Redis.Get[T](String key) 位置 D:\X\Src\NewLife.Core\Caching\Redis.cs:行号 406
   在 NewLife.Caching.Cache.BenchOne(Int64 times, Int32 threads, Boolean rand, Int32 batch) 位置 D:\X\Src\NewLife.Core\Caching\Cache.cs:行号 338
   在 NewLife.Caching.Redis.BenchOne(Int64 times, Int32 threads, Boolean rand, Int32 batch) 位置 D:\X\Src\NewLife.Core\Caching\Redis.cs:行号 598
   在 NewLife.Caching.Cache.Bench(Boolean rand, Int32 batch) 位置 D:\X\Src\NewLife.Core\Caching\Cache.cs:行号 303
   在 NewLife.Caching.Redis.Bench(Boolean rand, Int32 batch) 位置 D:\X\Src\NewLife.Core\Caching\Redis.cs:行号 586
   在 Test.Program.Test2() 位置 D:\360安全浏览器下载\NewLife.Redis-master\Test\Program.cs:行号 94
   在 Test.Program.Main(String[] args) 位置 D:\360安全浏览器下载\NewLife.Redis-master\Test\Program.cs:行号 26

**Comment by nnhy** [comment]
克隆源码，回到几个月之前的不同版本，看看是否还有这个问题。
也有几个月没跑这个压测程序了

**Comment by nnhy** [comment]
已确认为Redis管道模式BUG，已修正！
https://github.com/NewLifeX/X/commit/322e737629ebdb8c1ec7dba7e27ba9468db52324
