### ISSUE TITLE
List set 删除失败

### ISSUE THREAD

**Issue by nodyang** [NewLifeX/NewLife.Redis#41]
![image](https://user-images.githubusercontent.com/3090191/71617521-697d7400-2bf6-11ea-8880-4ab77d88be8c.png)
![image](https://user-images.githubusercontent.com/3090191/71617529-70a48200-2bf6-11ea-8ae9-3a1baf339eff.png)

1单个类删除都是没有问题的。
2 只要是嵌套类。删除都失败。

**Comment by nodyang** [comment]
![image](https://user-images.githubusercontent.com/3090191/71622128-b2412700-2c0e-11ea-815d-7d11ec25c508.png)
消息队列也有问题。是不是Mac环境的问题

**Comment by nodyang** [comment]
![image](https://user-images.githubusercontent.com/3090191/71622246-65aa1b80-2c0f-11ea-826b-114c7118e213.png)
这个版本么有问题。。

**Comment by nnhy** [comment]
很少使用list删除，实在需要，那就是hash更好；
你可以打开日志，看看两次序列化的内容是否不一致
