### ISSUE TITLE
加个栈功能

### ISSUE THREAD

**Issue by qq1078350533** [NewLifeX/NewLife.Redis#43]
不要 只有队列 还有栈可以加下

**Comment by nnhy** [comment]
Redis栈，右进右出 · NewLifeX/NewLife.Redis@efd5be1
https://github.com/NewLifeX/NewLife.Redis/commit/efd5be1825a6c65d79ccc13976e63705514e0bb3

已添加，你试试效果

**Comment by nnhy** [comment]
https://github.com/NewLifeX/X/commit/82f145be0bcd7d1e36eca948f9d0c1657cc19e8e
