### ISSUE TITLE
申明:此非BUG 提几个功能建议

### ISSUE THREAD

**Issue by AtlantisDe** [NewLifeX/NewLife.Redis#44]
# 申明:此非BUG 提几个功能建议
- 功能1:希望新增队列 Key对应里面的Items count查询支持
- 功能2:希望新增对 集合Set 里面Items 有序集合分页查询支持!
谢谢老大们.辛苦了.

**Comment by nnhy** [comment]
1，已支持（2020-1-11），RedisQueue.Count
2，有序集合已支持，分页查询 RedisSortedSet.Search
