### ISSUE TITLE
NewLife.Redis=>官方cluster  Rebalance 方法报错  Sequence contains no elements

### ISSUE THREAD

**Issue by edisonlovecarol** [NewLifeX/NewLife.Redis#45]
目前猜测   原因在于 当集群中  添加的节点均为master ，没有 任何slave的情况下 会出现这个报错。

**Comment by nnhy** [comment]
如果能提供详细异常栈就好了！
做了一点小修改，希望有效。

https://github.com/NewLifeX/NewLife.Redis/commit/e5f82d863189e6f0c2f1d09c647adcf439f25a89
