### ISSUE TITLE
SortedSet可否提供测试用例

### ISSUE THREAD

**Issue by QQ897878763** [NewLifeX/NewLife.Redis#47]
想通过有序列表做个灵活点的排行榜，可否有SortedSet的用例代码 谢谢

**Comment by nnhy** [comment]
排序集合 单元测试 · NewLifeX/NewLife.Redis@0f5faff
https://github.com/NewLifeX/NewLife.Redis/commit/0f5faffb03ce8f9e19a92d197d628480221b912a
