### ISSUE TITLE
Redis.Create没有这个方法

### ISSUE THREAD

**Issue by loveyeguo** [NewLifeX/NewLife.Redis#53]
我直接按官网复制案例，为什么提示没有这个方法呢？ 只能用  new FullRedis

**Comment by nnhy** [comment]
原来的Create静态去掉了，没有修改例程。。。
现在清一色 new xxxRedis

**Comment by loveyeguo** [comment]
原来如此 ，建议还是改一下Github上面的例子哈。 不然确实容易误导。   百度上面的也全部是create
