### ISSUE TITLE
redis集群不能自动切换节点

### ISSUE THREAD

**Issue by huguodong** [NewLifeX/NewLife.Redis#58]
三主三从，关掉一个主节点之后，直接报错连接失败也没有自动切换节点，再启用主节点报错，MOVED 原来的副节点

**Comment by nnhy** [comment]
10月份版本 newlife.core 里面的redis支持配置多个地址，第一地址故障时，使用后续地址

**Comment by nnhy** [comment]
自动切换节点已经完成，至于在启用主节点时报错，则是redis集群的问题。
实际工作中，更建议使用主从架构，redis集群限制太多。
