### ISSUE TITLE
增加批量操作的支持

### ISSUE THREAD

**Issue by jovi-Li** [NewLifeX/NewLife.Redis#61]
某些场景可能批处理会更加合适，比如订阅消息全部插入数据库
takemessage可以重载个取多条的方法 ？
提交消息好像可以一条命令提交多个把 ？
      foreach (var item in keys)
        {
            rs += Ack(Group, item);
        }

**Comment by nnhy** [comment]
发布消息支持一次性多条消息：
var rds=new FullRedis();
var q=rds.GetQueue<Object>(key);
q.Add("1234", "abcd", "dddd");

消费也支持多条，不过一般每次消费一条，阻塞更好用，也方便做确认

**Comment by nnhy** [comment]
轻量级消息队列RedisQueue 
https://www.yuque.com/smartstone/nx/redisqueue

**Comment by jovi-Li** [comment]
> 发布消息支持一次性多条消息：
> var rds=new FullRedis();
> var q=rds.GetQueue(key);
> q.Add("1234", "abcd", "dddd");
> 
> 消费也支持多条，不过一般每次消费一条，阻塞更好用，也方便做确认

我的意思是 消息支持取多条， 然后确认也支持多条同时确定  增加多条处理的方式是不是挺好的 ？
我这个碰到的场景是写入数据，一次写1条写20次和一次下20条还是有些区别的

**Comment by nnhy** [comment]
拉取消息和确认消息，都支持多条，但是实际使用建议一条条来。
假设取10条，处理正常，确认10条；如果有一条处理异常，想要确认9条，这样你的代码写起来岂不是非常复杂？

如果只是基于性能考虑，就完全没必要，因为redis每个指令都在1ms左右

**Comment by jovi-Li** [comment]
> 拉取消息和确认消息，都支持多条，但是实际使用建议一条条来。
> 假设取10条，处理正常，确认10条；如果有一条处理异常，想要确认9条，这样你的代码写起来岂不是非常复杂？
> 
> 如果只是基于性能考虑，就完全没必要，因为redis每个指令都在1ms左右

是插入数据库的性能 。

我测试了下 ，XAck FullQueue test  1612064425631-0 1612064423009-0  1612064426657-0  1612064426657-123  一个正确的参数 混合些不存在参数，不影响正确的参数提交   

批量提交 如果失败的 会在pending里面，再走重试也是可以的？

**Comment by nnhy** [comment]
你是想要每次消费多条，然后批量插入数据库？这样也挺好

**Comment by jovi-Li** [comment]
> 你是想要每次消费多条，然后批量插入数据库？这样也挺好

希望能加到主版本中 谢谢！

**Comment by nnhy** [comment]
var count = 100;
var msgs = await ReadGroupAsync(group, Consumer, count, timeout * 1000, cancellationToken);
var list = msgs.Select(e=>e.GetBody<Product>()).ToList();
list.Insert(true);
queue.Acknowledge(msgs.Select(e=>e.Id).ToArray());

如上，每次消费100条
