### ISSUE TITLE
当延时队列中成员为guid类型时，takeone无法获取成员

### ISSUE THREAD

**Issue by willingtolove** [NewLifeX/NewLife.Redis#65]
var queue = _redis.GetDelayQueue《Guid》(key);

 queue.Delay = 10;

 queue.Add(Guid.NewGuid());

 Thread.Sleep(10000);

 var v1 = queue.TakeOne(2);//无法获取到成员

**Comment by nnhy** [comment]
先转为字符串，然后按照字符串进行生产和消费，消费得到字符串以后，自己转一下guid

**Comment by willingtolove** [comment]
嗯嗯，是这样处理的。

**Comment by fairok** [comment]
> 先转为字符串，然后按照字符串进行生产和消费，消费得到字符串以后，自己转一下guid

虽然可以这样解决问题，但不知道能不能直接支持guid，可能会更好

**Comment by nnhy** [comment]
> > 先转为字符串，然后按照字符串进行生产和消费，消费得到字符串以后，自己转一下guid
> 
> 虽然可以这样解决问题，但不知道能不能直接支持guid，可能会更好

取决于编码器Encoder，你可以改一下提交PR
