### ISSUE TITLE
为什么数据删除不成功

### ISSUE THREAD

**Issue by zzguoxuefeng** [NewLifeX/NewLife.Redis#66]
我在redis的list当中放置一个mongo的大文档,通过一下的方法:
                var lstDb = fullRedis.GetList<T>(key);
                var data = lstDb.Where(n=>n.serviceId=="23232");
                foreach (var item in data)
                {
                    lstDb.Remove(item);
                }  
删除不成功.
如果放置的是小对象,就可以成功删除. 
这是为什么?
通过看调试日志,发现在LREM当中的显示日志,没有显示完要删除的对象.是不是对文档的大小有限制

**Comment by nnhy** [comment]
1，系统没有设置限制大小的问题你
2，日志只显示一部分，避免过大
3，你的这种场景，建议使用kv(string)结构，或者hash结构，然后按照key删除更合适

**Comment by zzguoxuefeng** [comment]
好,知道了 谢谢
