### ISSUE TITLE
RedisDelayQueue 如何初始化？

### ISSUE THREAD

**Issue by Luokun2016** [NewLifeX/NewLife.Redis#69]
Redis Queue可以直接使用_redis.GetQueue<T>(key) 获取，RedisDelayQueue如何获取？

NewLife.Redis版本3.9.2021.505

![image](https://user-images.githubusercontent.com/24650960/118617972-bc5cc900-b7f5-11eb-9c6e-722e53e60241.png)

**Comment by Luokun2016** [comment]
使用FullRedis 可以获取

**Comment by nnhy** [comment]
发布的时候，可以借助 RedisReliableQueue.AddDelay。
也可以 new RedisDelayQueue(fullRedis, key)
