### ISSUE TITLE
请问支持 rpoplpush 这个命令吗？

### ISSUE THREAD

**Issue by niunan** [NewLifeX/NewLife.Redis#7]
我想做个环状列表，在1，2，3，4，5几个元素内不停的循环，
![tim 20181022173000](https://user-images.githubusercontent.com/7498393/47286199-45043000-d620-11e8-86f1-422d03a48d25.png)
上面是我的代码，取出list中的第一个元素，然后删除掉第一个，再rpush把元素加到最后，本地测试没发现问题，但是在放到生产环境中发现有时在添加到列表结尾的时候会多添加重复的。。
让列表变成是 2,3,4,5,1,1 这样的。。
可能是我在添加到列表结尾的之前又有另一个线程进来取列表元素了，然后2个线程都把1加到了列表结尾了，自己查了下，找到rpoplpush 这个命令，不知道这个支持不支持。。。

**Comment by nnhy** [comment]
rpoplpush命令没有封装，可以参考其它命令调用Execute封装一下，一行代码可以搞定。

你的逻辑用错了，如果是想拿掉第一个，一定是pop弹出，上面这样子先拿出来再回头删除，一定有多线程冲突问题。

你可以用另一个封装 RedisQueue，而不是RedisList。
var rq = rds.GetQueue<String>(userid+"_noremal");
var us = rq.Pop(1);
