### ISSUE TITLE
使用可信队列导致 redis 中的Status，ACK暴增

### ISSUE THREAD

**Issue by 2251754654** [NewLifeX/NewLife.Redis#72]
![image](https://user-images.githubusercontent.com/22870839/134603148-ad7dc802-baa7-44f2-8b98-ded92c811bba.png)
试了各种方法，设置name或者用户名啊没用，查看源码，后缀取了个随机数，怎么解决呢？

**Comment by nnhy** [comment]
可信队列，队列对象必须使用单例！特别是消费者，一定一定要用单例。
因为每一个消费者都会生成一个随机id，用于建立专用Ack队列，避免多消费者之间争夺消息。

**Comment by 2251754654** [comment]
那不断关闭重启也会出现多个，无用的会自动删除吗

**Comment by nnhy** [comment]
这些key会过期然后自动删除。
只有开发阶段才会不断的重启吧，生产环境应该很少重启
