### ISSUE TITLE
单例使用中如何切换数据库

### ISSUE THREAD

**Issue by luoxgwb** [NewLifeX/NewLife.Redis#77]
`ICache` 接口没有 Db 属性。

以下代码实测依然会往 db=0 中写入
```` C#
var redis= new FullRedis();
redis.Init(config); // config: "127.0.0.1"
redis.Db = 5;

services.AddSingleton<ICache>(redis);
````

// 这样正常
```` C#
var redis= new FullRedis(config, null, 5);
````

**Comment by nnhy** [comment]
使用方法没有问题，试试打开日志，观察它是否切换了数据库
redis.Log = XTrace.Log
打开日志后，会输出每一个redis操作到日志里面

**Comment by nnhy** [comment]
`public override void Init(String config)
{
    if (config.IsNullOrEmpty()) return;

    if (config == _configOld) return;
    if (!_configOld.IsNullOrEmpty()) XTrace.WriteLine("Redis[{0}]连接字符串改变！", Name);

    var dic =
        config.Contains(',') && !config.Contains(';') ?
        config.SplitAsDictionary("=", ",", true) :
        config.SplitAsDictionary("=", ";", true);
    if (dic.Count > 0)
    {
        Server = dic["Server"]?.Trim();
        UserName = dic["UserName"]?.Trim();
        Password = dic["Password"]?.Trim();
        Db = dic["Db"].ToInt();

        if (Server.IsNullOrEmpty() && dic.TryGetValue("[0]", out var svr)) Server = svr;

        // 连接字符串可能独立写了port
        var port = dic["Port"].ToInt();
        if (port > 0 && !Server.Contains(':')) Server += ":" + port;

        if (dic.TryGetValue("Timeout", out var str))
            Timeout = str.ToInt();
        else if (dic.TryGetValue("responseTimeout", out str))
            Timeout = str.ToInt();
        else if (dic.TryGetValue("connectTimeout", out str))
            Timeout = str.ToInt();

        if (dic.TryGetValue("ThrowOnFailure", out str))
            ThrowOnFailure = str.ToBoolean();

        if (dic.TryGetValue("MaxMessageSize", out str) && str.ToInt(-1) >= 0)
            MaxMessageSize = str.ToInt();

        if (dic.TryGetValue("Expire", out str) && str.ToInt(-1) >= 0)
            Expire = str.ToInt();
    }

    // 更换Redis连接字符串时，清空原连接池
    if (!_configOld.IsNullOrEmpty()) _Pool = null;

    _configOld = config;
}
`

**Comment by luoxgwb** [comment]
`redis.Log = NewLife.Log.XTrace.Log;` 必须写在 `Init()` 前面，否则无法记录 redis 操作日志。

最终记录日志如下，没有执行切换数据库操作（`SELECT 5`）：
`new FullRedis(config, null, 5)` 则会执行 切库 操作

```` log
#字段: 时间 线程ID 线程池Y/网页W/普通N/定时T 线程名/任务ID 消息内容
#Fields: Time ThreadID Kind Name Message
09:17:48.971  1 N - NewLife.Core v8.11.2021.1204 Build 2021-12-04 07:26:10 .NETCoreApp,Version=v6.0
09:17:48.976  1 N - NewLife组件核心库 ©2002-2021 NewLife
09:17:48.976  1 N - App v1.0.0 Build 2000-01-01 .NETCoreApp,Version=v6.0
09:17:48.976  1 N - App 
09:17:48.977  1 N - Redis使用 Tcp://127.0.0.1:6379
09:17:49.034  1 N - Redis使用 Tcp://127.0.0.1:6379
09:17:49.034  1 N - FullRedisPool.Init NewLife.Caching.RedisClient Min=2 Max=1000 IdleTime=20s AllIdleTime=120s
09:17:49.035  1 N - => INFO
09:17:49.039  1 N - <= $4177 # Server
redis_version:6.2.6
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:84dfb40eb1119e5
redis_mode:standalone
os:Linux 5.10.16.3-microsoft-standard-WSL2 x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:10.2.1
process_id:1
process_supervised:no
run_id:0e836ed0c7c386b5055e8f7a8be4599d001dbe0c
tcp_port:6379
server_time_usec:1642987069038517
uptime_in_seconds:2258
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:15597116
executable:/data/redis-server
config_file:
io_threads_active:0

# Clients
connected_clients:3
cluster_connections:0
maxclients:10000
client_recent_max_input_buffer:16
client_recent_max_output_buffer:0
blocked_clients:0
tracking_clients:0
clients_in_timeout_table:0

# Memory
used_memory:1126264
used_memory_human:1.07M
used_memory_rss:13070336
used_memory_rss_human:12.46M
used_memory_peak:1392816
used_memory_peak_human:1.33M
used_memory_peak_perc:80.86%
used_memory_overhead:847824
used_memory_startup:80988
09:17:54.050  9 Y T FullRedisPool.Release New=1 Release=0 Free=1 Busy=0 清除过期资源 0 项。总请求 1 次，命中 0.00%，平均 172.80us
09:17:59.394 18 Y P => GET Cache:EB10AA753B57E098
09:17:59.396 18 Y P <= $-1
09:17:59.482 17 Y P => SADD Cache:Info Cache:EB10AA753B57E098
09:17:59.483 17 Y P <= :1
09:17:59.487 17 Y P => EXPIRE Cache:Info 7200
09:17:59.488 17 Y P <= :1
09:17:59.494 17 Y P => SET Cache:EB10AA753B57E098 [4218]{"TableRows"...............} EX 7200 NX
09:17:59.496 17 Y P <= +OK

````
