### ISSUE TITLE
能开源NewLift.Core吗

### ISSUE THREAD

**Issue by bishopjun11** [NewLifeX/NewLife.Redis#8]
能开源NewLift.Core吗？什么时候？

**Comment by bishopjun11** [comment]
https://github.com/NewLifeX/NewLife.Core

**Comment by bishopjun11** [comment]
都3年没有更新了

**Comment by nnhy** [comment]
https://github.com/NewLifeX/X
这个才是X组件核心库

你发的那个是以前的备份
