### ISSUE TITLE
单例模式下，切换数据库无效？

### ISSUE THREAD

**Issue by pinzi** [NewLifeX/NewLife.Redis#80]
断点调试发现db是改变了的，不知道为啥数据最后还是写入了默认的数据库0。
![微信截图_20220217132916](https://user-images.githubusercontent.com/3843463/154411690-e6fb3ad9-d048-4d07-ac4a-e94a61d647f3.png)
![微信截图_20220217133030](https://user-images.githubusercontent.com/3843463/154411692-3a89d2a2-e37d-469d-b945-b5c60be9a5af.png)

**Comment by pinzi** [comment]
![image](https://user-images.githubusercontent.com/3843463/154411780-3ec808b7-f081-47d9-be31-3aeb3752bc60.png)

**Comment by pinzi** [comment]
能否将.NET Framework的支持升级到4.8

**Comment by nnhy** [comment]
我再看了一次标题，终于明白你的问题了。
你是想在使用中切换db，这是不行的，因为FullRedis内部有个连接池，用了一段时间后，会保留若干RedisClient的实例。而每个RedisClient内部保持一个Tcp连接，已经做过密码验证和db选择。因此，即使修改了db，在做新的操作时，如果连接池返回原来的连接实例，那么就还是以前的那个db。当然，新增连接会使用新的db。

**Comment by nnhy** [comment]
根据设计，你可以在修改db后，清空连接池  Redis.Pool.Clear()。
一般建议不要在使用过程中切换db，而是根据不同的连接字符串（如server=127.0.0.1;password=xxx;db=3;timeout=5000）建立不同的Redis对象。

**Comment by pinzi** [comment]
好吧，了解了，谢谢。
