### ISSUE TITLE
Support for Redis SUB/PUB

### ISSUE THREAD

**Issue by ehinolakingsley** [NewLifeX/NewLife.Redis#81]
Hi,

Firstly let me commend your effort in creating such a highly quality library. 
I do have a request.

Is there by any chance Redis Sub/Pub is coming soon or is it available already because i can't see it in any documentation.

Thanks

**Comment by nnhy** [comment]
NewLife.Redis/PubSub.cs at master · NewLifeX/NewLife.Redis
https://github.com/NewLifeX/NewLife.Redis/blob/master/NewLife.Redis/PubSub.cs

NewLife.Redis/PubSubTests.cs at master · NewLifeX/NewLife.Redis
https://github.com/NewLifeX/NewLife.Redis/blob/master/XUnitTest/PubSubTests.cs
