### ISSUE TITLE
Feature Request: English documentation and comments

### ISSUE THREAD

**Issue by jeroenhabets** [NewLifeX/NewLife.Redis#84]
Hi @nnhy,

We find your library very useful but proliferation of Chinese documentation and comments makes it harder to adopt for us as a non-Chinese company.

Am I the first to approach you about that?

Would you be open for English documentation? Same question for code comments?
As a non-Chines speaker, I could only contribute if Google Translate with some English corrections would be acceptable.

Kind regards,
Jeroen Habets

**Comment by Soar360** [comment]
I will add an English version of the readme file as soon as possible.Thanks for your advice.

**Comment by jeroenhabets** [comment]
Hi @Soar360,

Thanks a lot! I was going to suggest https://www.deepl.com/translator or translate.google.com but found your English readme already:

https://github.com/NewLifeX/NewLife.Redis/blob/master/Readme.en.md

Thank you again!
Jeroen Habets
