### ISSUE TITLE
批量消费获取时怎么知道还有哪些消息是未被消费确认的？

### ISSUE THREAD

**Issue by pinzi** [NewLifeX/NewLife.Redis#89]
![image](https://user-images.githubusercontent.com/3843463/197965822-41567897-fc41-4798-99de-61e1f530fa69.png)

请问一下，Take多条消息时，循环列表逐条消费，逐条ack，怎么获取列表中那些还未被ack的消息呢？

**Comment by nnhy** [comment]
没办法知道。
Take消费得到的消息，都是没有被效果过，或者已经消费但是很长时间没有Ack确认。

**Comment by pinzi** [comment]
> 没办法知道。 Take消费得到的消息，都是没有被效果过，或者已经消费但是很长时间没有Ack确认。

take的消息是不是存在另外一个key里面，ack的时候才会被移除，那能不能获取到这个key里面的消息呢？
我遇到个情况是，我每次都是批量消费，但是消费的速度有点慢，想知道到底多少消息已经take了还在等待消费ack确认。
