### ISSUE TITLE
希望支持一下tls/ssl模式的访问连接

### ISSUE THREAD

**Issue by Sam--Shan** [NewLifeX/NewLife.Redis#91]
目前基于一些云paas提供的redis资源，提供的连接终结点，会默认使用tls/ssl模式，从安全性的角度，最好能支持一下tls/ssl.

**Comment by nnhy** [comment]
已提交SSL支持，需要帮忙测试验证一下

**Comment by Sam--Shan** [comment]
@nnhy  nuget更新了最新的预览版。然后测试了一下，可以用tls12了。感谢。方便的话，发一下正式版把。

**Comment by nnhy** [comment]
一般是每个月初发正式版，你先用着现在这个beta版好了，除了TLS没有其它更新

**Comment by Sam--Shan** [comment]
好的 感谢！
