### ISSUE TITLE
使用主从库读写分离的时候，无法自动切换可以写入的库

### ISSUE THREAD

**Issue by esladol** [NewLifeX/NewLife.Redis#95]
当报错为READONLY You can't write against a read only replica.
无法自动切换到可以写入的库进行set
目前是必须要可写入的主库在配置的第一个。

**Comment by nnhy** [comment]
最近两个月优化集群、主从和哨兵的支持。
1，启动时，自动根据info识别工作模式：集群、主、从、哨兵，主动探测发现所有节点，统称IRedisCluster
2，FullRedis对象每次执行命令时，根据key去IRedisCluster里面选择节点
3，IRedisCluster内有定时器自动发现节点变化，60秒一次
因此FullRedis支持自动切换到可用的主从节点，但是有最大60秒的沉默期。
