### ISSUE TITLE
队列阻塞读取的时候有个bug希望修复一下，队列获取不到数据的时候会报错，类型转换会报错

### ISSUE THREAD

**Issue by chuzhuming** [NewLifeX/NewLife.Redis#97]
![redis bug](https://user-images.githubusercontent.com/8085613/233250599-cce15609-b385-487b-b782-1f91e07edc06.jpg)

**Comment by nnhy** [comment]
查了代码，这个TryChange当value为null的时候，所有if都不匹配，最后会return false

**Comment by chuzhuming** [comment]
![redis bug](https://user-images.githubusercontent.com/8085613/233555623-e5887223-eaa8-4c9a-a65d-9fc8f2fff2d2.jpg)
![redis bug1](https://user-images.githubusercontent.com/8085613/233555633-c5cd87bc-8066-403d-9678-6c77890096ac.jpg)

看代码，是这里面的elmType为null，不是value

**Comment by chuzhuming** [comment]
![redis bug2](https://user-images.githubusercontent.com/8085613/233556093-02188b4d-f720-4815-b292-b298ca1b8271.jpg)

调用代码
