### ISSUE TITLE
提个问题使用ReliableQueue队列时链接redis指定的时db=3,偶尔程序会自动切到db=0上

### ISSUE THREAD

**Issue by lkd3063601** [NewLifeX/NewLife.Redis#98]
redis版本：阿里云 社区版 | Redis 5.0 | 8G集群版（8节点）
NewLif.Redis版本：5.3.2023.401
出现问题的场景：程序部署在K8S上 pod数量改成2 就是部署2份或者多份时，来回伸缩（2变4，4变1，1变5等）测试时，发现它有时会访问到0数据库中， appsettings.json中的DB设置的是3，看了源码也不知咋改，最后直接使用数据库0了

![TNS)NQNJRF@2@F7HGQFW6(0](https://user-images.githubusercontent.com/15059204/233276762-4f20d6a3-dc4b-4731-9ad5-a9da1cb18160.png)
![)U7925RR0QL}C~UW1 O NWB](https://user-images.githubusercontent.com/15059204/233276835-c568bbb9-704e-4e59-aee3-5f749a864f54.png)
![9RR 2K%SR0{ W`80)VTU)@G](https://user-images.githubusercontent.com/15059204/233277569-5715d548-a38b-47a9-ab0b-e2581fcae8ed.png)
![HCT`}9@8I%%Q@I%U{ZX` 75](https://user-images.githubusercontent.com/15059204/233276900-4ed02274-0fb4-4066-adc4-8c09f0c8fd16.png)

![9RR 2K%SR0{ W`80)VTU)@G](https://user-images.githubusercontent.com/15059204/233277636-55363782-b1c2-4c39-b819-292a853b3e79.png)

**Comment by nnhy** [comment]
打开日志，redis.Log=XTrace.Log，然后查看日志文件，它会显示“选择节点。。。”
还有就是通过星尘APM，观察异常发生时做了什么动作。
最近3月和4月针对集群功能做了优化，可能影响到Db选择，可通过回滚到0201版本看问题是否仍然存在。

**Comment by lkd3063601** [comment]
开了日志 ，上面没见da打印“选择节点。。。” 只看到AUTH 后，就变成0数据库了
![image](https://user-images.githubusercontent.com/15059204/233535169-9c6dd2f1-64e9-4ff3-b709-b450f0730640.png)

**Comment by nnhy** [comment]
你的日志限制，一直都是Db=3啊，对于非0的Db，会有一个 Select 3 这样的命令

**Comment by lkd3063601** [comment]
对，日志上是显示3但是实际操作得是0
![image](https://user-images.githubusercontent.com/15059204/233550967-450ba7b0-5ac6-4c76-84bf-c21a4c2c7ef4.png)

**Comment by lkd3063601** [comment]
![1682057238356](https://user-images.githubusercontent.com/15059204/233554017-fbad0537-2c04-423a-a4a3-bba39a8b5db0.jpg)
看日志正常出现AUTH 时后面就会跟上 打印个 SELECT 3 例如上面图，下图出现问题时 AUTH 后面就没有打印 SELECT


![1682057364438](https://user-images.githubusercontent.com/15059204/233554037-c1a317a8-426f-49b4-9272-5902a2de41fe.jpg)

**Comment by lkd3063601** [comment]
刚又测试，程序就一份在运行，前后操作间隔2s内，就出现问题了

![image](https://user-images.githubusercontent.com/15059204/233556923-70445644-4811-405f-b9fd-c3a93aa8bc35.png)

下图证明操作到db=0上了
![image](https://user-images.githubusercontent.com/15059204/233556149-5ba5a28b-193f-4d18-bfc3-388afa8fa9d1.png)

**Comment by lkd3063601** [comment]
然后继续执行时又自动切回db=3了但产生得消息，也消费不到了，日志上面也没显示 BRPOPLPUSH 记录了
![image](https://user-images.githubusercontent.com/15059204/233561118-ead53455-644d-4383-b028-b698120b97d1.png)
![image](https://user-images.githubusercontent.com/15059204/233561881-2548f625-c343-4019-999c-b77fea18d8eb.png)

**Comment by lkd3063601** [comment]
后面我在本地测试 redis连接阿里云得，本地就运行程序，运行关闭-运行关闭 这样来回测也会出现上面得问题，看起来就是来回重新运行程序时就会出现问题 。和一份程序部署多个没关系

**Comment by lkd3063601** [comment]
已解决，原因是消费时连接自动断开了，导致TakeOneAsync 时，出现异常了，由于放在了新的线程中也没有try  catch，就没有抛出异常，程序中断了，包一层try  catch就好了，出现异常捕捉到，后面FullRedis自动重连就好了。
在 var mqMsg = await queue.TakeOneAsync(10); 外 try catch 下
![image](https://user-images.githubusercontent.com/15059204/234740428-858e2d02-fc44-4513-9a41-cc07068110c2.png)
